### ISSUE TITLE
Torch Does Not Stop Mob Spawns on Servers

### ISSUE THREAD

**Issue by Darkosto** [Xalcon/TorchMaster#1]
Hello! 

Thanks for the mod, it has been working out great for single player worlds. I've been doing some server testing and it seems to not stop mobs from spawning on a server. Is there a way to allow this to work for SMP?

Mod Version: 1.0.1
Forge: 2171
MC Version: 1.10.2

Thank you :)
Darkosto

**Comment by Xalcon** [comment]
Sorry for the delayed response.
I have the torch running on my server and its working fine. Can you verify that mobs are actually spawning inside the radius? The torch doesnt prevent mobs from walking into the torch radius. If I'm not mistaken, the torch also should not prevent mob spawning from non-natural sources (like mob spawners).

Also double check the Version. I fixed a bug related to mob spawning when using torches in multiple dimensions.

**Comment by Darkosto** [comment]
Okay! Let me check myself. I had the report from one of the FTB testers on the server. I'll load up a new server today and check it out and get back to you :)

**Comment by Darkosto** [comment]
Tested and works just fine on servers! Thanks for the response :)

**Comment by Hund** [comment]
It does prevent mobs from spawning via mob spawners on SMP in Minecraft 1.10.2. Let me know if you want me to open a new issue. :)

**Comment by Xalcon** [comment]
@Hund this is actually intended. The torch is an exact replica of the Extra Utilities Magnum Torch which prevents only mob spawning from natural events (Low light level). I dont want to prevent spawning from mob spawners so you can still create mobfarms in your base.

**Comment by Xalcon** [comment]
yes, please open a new issue.
