### ISSUE TITLE
[1.14.4] Mod doesn't work on servers

### ISSUE THREAD

**Issue by Gbergz** [Xalcon/TorchMaster#100]
Hello! The newest version of Torchmaster "2.0.0.7-rc0." (the re-write i guess) doesn't work on servers!

It boots like normally but you're not able to join the server, constantly disconnects you with messages like "Timed Out", "Disconnected" & "Error something" message.

I do not have a crash-report or similar and it's also difficult to locate the errors in the logs.
I went through 210 mods server-side. And finally found which mod it is.
Downgrading the mod to version "2.0.0.6-alpha" instead of using "2.0.0.7" makes me able to login without any issues, no disconnecting.

**Comment by Xalcon** [comment]
this is odd, i've just tested this in my dev environment and the server works just fine.
Might be a different mod clashing with torchmaster somehow.
I'll need more information to troubleshoot this further, specifically the laters.log file and the forge version used.
