### ISSUE TITLE
All placed Mega Torches on server deactivated upon server restart

### ISSUE THREAD

**Issue by katubug** [Xalcon/TorchMaster#101]
As I was writing up this report, I half-answered my issue. I had run the `/torchmaster_torch_list` command and noticed that only 3 torches were visible, and they were all at the reporting player's base. The one at my base, next to which I was standing, was not on the list. I placed a new one right next to it, ran the command again, and the new one was listed correctly.

Here is the original list, plus one after I'd realized the issue and my player and I had replaced some of them: https://pastebin.com/kvHf9BDx

I am not sure what could have caused them to deregister/unload/whatever exactly happened. As I mention in the original post, the only change we made was to swap one backups mod for another. The logs included were from when the issue was first noticed, however I do have some prior to that if you think they'd be useful.

Let me know if I omitted anything! Thanks for your time, and for the excellent mod!

#Original post below for context:

* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2838-universal
* **Modpack version** (links to current modlist): [1.7.3](http://enthusiasticraft.cf/modpack-update-1-7-3/#modlist)
* **Mod versions:** torchmaster_1.12.2-1.8.0.79, Backups-1.12.2-1.4.7?

So today on my server, we discovered that Mega Torches had just stopped working. Mobs were spawning well within the 64-block radius. I attempted to replicate in singleplayer but could not. However, I checked other Mega Torches on the server and they were having the same issue.

We have been using Torchmaster for a long time with no issues, this is brand new as of our morning restart, as far as we can tell. The only change we've made recently was that we switched from FTB Utilities Backups to [Backups](https://www.curseforge.com/minecraft/mc-mods/backups) for our world saving needs.

This person is the only trace we could find of this issue, and it's not super helpful:
https://www.curseforge.com/minecraft/mc-mods/torchmaster?comment=141

latest.log: https://paste.ee/p/T7tZV
debug.log was too big to include the whole file, so I clipped (hopefully) relevant lines: https://pastebin.com/W9MRABEq
torchmaster.cfg (just downloaded from server): https://pastebin.com/EB9AyeXe

**Comment by Xalcon** [comment]
Thank you for your detailed report. I'm currently at work so I can't do an indepth investigation on this. On my local dev environment I'm unable to reproduce this issue. Torchmaster on its own works just fine - in singleplayer and multiplayer.

The way torchmaster "remembers" torch positions across reboots is via the world capability system. It seems some other mod is messing with this system in some way. 

I've talked to the guy you are referring to (the comment on the torchmaster curseforge page) and I was unable to reproduce the issue with his mod setup - but he couldn't send me his whole folder, so I'm glad you are experiencing this with a pack that I can actually download. (Also I'm sad that this issue exists in the first place, but that's a different story :D)

Can you verify if this issue happens in single player or if it is a multiplayer only issue?

**Comment by katubug** [comment]
Thus far I've been unable to replicate it in singleplayer even between sessions. I have a suspicion that the issue was due to the world being unable to be saved properly due to lack of disk space.

I was using the mod Backups and mistakenly configured it to keep too many copies - that's a and unrelated story, but here's a relevant link: https://github.com/Silly511/Backups-Mod/issues/11

As you can see in the logs there, the server was having trouble writing to disk. I don't know whether this was occurring when the first "reset" occurred, however.

But it seems like a good lead. I'm not sure how to test it further though. Additionally, our server's nightly restart has happened, and when using the torch list command, I see all the mega torches I placed last night before bed.
