### ISSUE TITLE
[1.14.4] Client Crash - Placing a feral flare lantern - NullPointerException: Tesselating block model

### ISSUE THREAD

**Issue by ProsperCraft** [Xalcon/TorchMaster#102]
https://gist.github.com/ProsperCraft/79398a197ebe60d59c0a6dbd5e896c55

I was decorating spawn in creative and my client crashed instantly when placing a feral flare lantern.

Forge - forge-1.14.4-28.1.44
Mod- torchmaster-2.0.0.7-rc0
Modpack- https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by ProsperCraft** [comment]
Client crashes again when logging in to the server - 
https://gist.github.com/ProsperCraft/60c58b70f7c4cf012cba9e5ba06a06e4

**Comment by Xalcon** [comment]
That's interesting. I tried reusing my 1.12 blockstate code to make use of submodels but it didn't work - it just didn't render the submodel part - so i left it in.. Looks like forge added something new and now it crashes. I'll look into it.

**Comment by Xalcon** [comment]
fixed in 2.0.0-rc1, available on curseforge.

**Comment by Sandriell** [comment]
@Xalcon This doesn't appear to be fixed with 2.0.0-rc2.

Instantly crashed when placed and now crashing when logging in.

https://gist.github.com/Sandriell/640d12a004faa27dacc2be07a42b4464

**Comment by Xalcon** [comment]
The bug itself was fixed, it just looks like that octarine-core is messing something up (part of better foliage). I've tried better foliage and torchmaster in a clean instance of 1.14.4 but I was unable to replicate the crash. You could try removing better foliage to see if the game still crashes on load.

**Comment by Sandriell** [comment]
@Xalcon Removing Better Foliage allowed me to load the world without crashing. Thanks.
