### ISSUE TITLE
Decrease hitbox of Feral Flare Lantern to match model

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Xalcon/TorchMaster#103]
![image](https://user-images.githubusercontent.com/18755309/67823790-6cdb6e80-fa92-11e9-9729-3e06e7c54e2d.png)

The hitbox currently takes up a full block.

Using version 1.8.0.79 for 1.12.

**Comment by Xalcon** [comment]
Fixed in Torchmaster 1.8.1 for MC 1.12.2
