### ISSUE TITLE
[Feature request] Make TorchMaster compatible with BloodMoon

### ISSUE THREAD

**Issue by GrzechuGrek** [Xalcon/TorchMaster#107]
Great mod!
Well, I'm request you to make this mod compatible with BloodMoon mod, by adding configure option to enable/disable area protection during blood moon event.

**Comment by Xalcon** [comment]
Generally not a bad idea, but the bloodmoon mod didnt have an update in over 1.5 years and it doesnt have an API to check if there is currently a bloodmoon active. If lumien decides to get the mod running on 1.14 (and include an API to check for the current bloodmoon state or atleast have an event fired when a bloodmoon occurs), I would be happy to implement this.

For 1.12 this is rather unlikely.
