### ISSUE TITLE
Doesn't work with spawners.

### ISSUE THREAD

**Issue by culturedminecrafter** [Xalcon/TorchMaster#108]
I tried it with enhanced mob spawners, no luck. Then i used a regular mob spawner, and that didn't work either. It's for my mob farm. It said in a forum that the torch doesn't prevent mob spawning.

**Comment by culturedminecrafter** [comment]
Version:1.14.3

**Comment by Xalcon** [comment]
~~I've just tried it and I'm unable to replicate your issue. Vanilla spawners keep working just fine while a torch is up~~
![image](https://user-images.githubusercontent.com/5042450/70377554-217c7180-1916-11ea-964f-60bfdf615e76.png)
nvm, didnt see the 1.14.3 post of yours.

**Comment by Xalcon** [comment]
I'm unable to replicate this. Even in 1.14.4 this is working perfectly fine. Please make sure you are actually running MC 1.14.4 and not 1.14.3.
