### ISSUE TITLE
Terrain Lighter not placing torches in protected land 1.12

### ISSUE THREAD

**Issue by habude** [Xalcon/TorchMaster#109]
I am running a forge server for my friends and have just added the TorchMaster mod to the server. Once I made the Terrain Lighter, added a few stacks of torches, a stack of coal and a lever next to it I powered it on. I could hear the sounds of torches being placed but none were set.

It seems to be an issue with MineColony. When you place the colony you assign players permissions to be able to edit the area, the Terrain Lighter does not seem to inherit the permissions from the player who placed it.

Is there a workaround for the Terrain Lighter to place the torches in protected areas?

**Comment by Xalcon** [comment]
At the moment I'm using a fake player to place the torches. Using the actual player is theoretically possible, but would most likely break when the player is offline. I'll need to investigate this further.

**Comment by Xalcon** [comment]
I'll close this since 1.12 is no longer an actively supported version of mine.
