### ISSUE TITLE
Mega Torch prevents ExU2 Spawners from working

### ISSUE THREAD

**Issue by Xalcon** [Xalcon/TorchMaster#11]
According to the youtuber Hypnotizd, the mega torch prevents ExU2 spawners from working. Need to investigate.

**Comment by Xalcon** [comment]
Just tested with **cursed earth** (working) and the **Resturbed Mob Spawner** (not working).
I'll take a closer look into the mob spawning code, hopefully I can use the workaround used in #2

**Comment by Xalcon** [comment]
I'm using pretty much the same work around

**Comment by RedSnt** [comment]
I realize this issue has been closed for half a year, and the fix does partially work. But I found that I had to break the mega torch and place it down again in order for ExU's resturbed spawner to start working. After that it works fine.

**Comment by Iomega0318** [comment]
Glad I went searching for an answer, I noticed this issue as well. I was wondering why even though it is supported the Extra Utilities 2 Spawners were still not spawning, cursed earth was working fine. Found this issue and indeed, breaking and replacing the torch does fix the issue. Odd.
