### ISSUE TITLE
[1.12.2/1.8.1.81] Feral Flare Lanter only lights up small area / no range range

### ISSUE THREAD

**Issue by AkiSan0** [Xalcon/TorchMaster#111]
Hi, im playing PO3 and wanted to have a nice light source and was very satisfied with the lantern in DDSS. 

First thing i tried was the mega torch and it works perfectly as well as the range slider for it. 

After that i tried the flare lantern and it seems to have some issues with this pack: 
1) some created light sources seem to be persistent even after breaking the lantern. chunk loading through various means didn't help.
2) the range does not increase or decrease. (slider)
3) it seems stuck on a radius on around 6-8 blocks. 
4) i'm missing the "incremental increase" from DDSS where it slowly filled a giant area

is this a known issue with the pack or is there some mod interference? do you need some sort of dump?

**Comment by Xalcon** [comment]
1. Lights decay slowly over time after the lantern is broken. You can speed up the process by using a frozen pearl.
2. I'm not sure what slider you are talking about. I only have a textbox, setting the default radius to 16 blocks. I've tested setting it to 4, 16 and 32, see screenshots below.
3. Are you sure the lantern is placing any lights at all? The lantern itself emits just as much light as a normal glowstone block. 
4. I'm not sure what to do here. It's clearly working in other modpacks as well as locally in my dev environment. I'm not the author/maintainer of PO3, so I have no idea what could cause the torch to not do anything.

Please make sure you have the tick rate set higher than 0 - as this would technically disable this functionallity - even though it should not be possible to set this value that low. Also make sure you dont set the radius too high. The lantern only tries placing light sources every few ticks and it is also random at that.

![image](https://user-images.githubusercontent.com/5042450/71378144-0a50ab80-25c7-11ea-890c-2ed18cb18f6f.png)
![image](https://user-images.githubusercontent.com/5042450/71378033-90202700-25c6-11ea-8785-6f6078118b4d.png)
![image](https://user-images.githubusercontent.com/5042450/71378045-a29a6080-25c6-11ea-9039-acf8705f77f7.png)
![image](https://user-images.githubusercontent.com/5042450/71378055-b5149a00-25c6-11ea-97d7-4e46981f6cee.png)

**Comment by Xalcon** [comment]
I just checked the PO3 install files and Torchmaster is not part of the pack. Did you add torchmaster on your own?

**Comment by Xalcon** [comment]
Ok, so I just installed Project Ozone 3 V3.1.45 and added Torchmaster 1.8.1.81, created a superflat world, changed the feral flare lantern range to 32 and put down the lantern:
![image](https://user-images.githubusercontent.com/5042450/71379255-f3ac5380-25ca-11ea-89b1-350c9496b589.png)
looks good too me.

**Comment by AkiSan0** [comment]
Hi, thank you for the quick answer! 

ofc. i meant the text box.. my bad.  :)

i just tried it higher up in my world, flew up some more and watched it from far above (like you did) and it works fine. i think some settings in DDSS made it seem less "spotty" as in PO3. 

maybe this was confusing me as well as some other interference like other light sources overlaying the flare lantern pattern. 

Maybe, as i was quite low in the world and just didnt wait long enough i haven't seen any effect in my previous testing.

As you stated: "The lantern only tries placing light sources every few ticks and it is also random at that." 

I hope this didnt waste too much of your time! Thank you very much for your testing and replies!! 

I will close it as it is "fixed" (though it was never a bug, just bad circumstance). 👍

**Comment by Xalcon** [comment]
If you want the lantern to be less "spotty", you can increase the minimum light level in the config. By default the lantern tries to keep the light level just above 10. Increasing this to 15 would cause the lantern to place a light literally any empty space it can. If you go that route, you might need to increase the light hardcap per lantern from 255 to something higher. The default range of the lantern is somewhere around (16 * 2 + 1)^2 * 8 = ~8700
I've set this hardlimit to counter a potential bug that would be caused by big tileentities (the Lantern tracks the location of each invisible light it places). I've no experience with settings that go this high, but you could check the settings DDSS used and apply them to your PO3 instance. 

Merry Christmas. :)
