### ISSUE TITLE
Dread Lamp has misplaced particles

### ISSUE THREAD

**Issue by toddnollan** [Xalcon/TorchMaster#112]
The dread lamp, in addition to particles spawning at x=x, y=y, z=z, has particles spawning at z=x.
[Example](https://gyazo.com/e64dd41fc35445227e552f985185ee90): Dread lamp at 5,64,2 is spawning particles at 5,64,5. If moved to 4,64,2, spawns additional particles at 4,64,4.

torchmaster_1.12.2-1.8.0.79.jar
ftb Revelations modpack
Using Optifine shader packs.

**Comment by Xalcon** [comment]
fixed in 1.8.2
