### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by SoyJetixXD** [Xalcon/TorchMaster#119]
Hello, Nice to talk to you, my friends and I have made a translation of the mod in Spanish, since your mod is one of our favorites, so we have spoken it and we want to give you our translation, if you wish.
Thank you for reading. 

[en_es.zip](https://github.com/Xalcon/TorchMaster/files/4424958/en_es.zip)

**Comment by Xalcon** [comment]
Added to the 1.12 branch. I'll prepare a release later. There are a few potential bugs I need to check before I want to release these changes.
