### ISSUE TITLE
(question) Does the torch stop grimoire of gaia mobs?

### ISSUE THREAD

**Issue by Zeusanite** [Xalcon/TorchMaster#12]

**Comment by Xalcon** [comment]
The last time I used GoG in a pack was back in 1.7.10 and those mobs spawned like any other mob depending on natural spawning rules. The Mega Torch should block these spawns unless they are spawned by non-natural means like mob spawners.

I will test this later if I find some time.

**Comment by Xalcon** [comment]
Mega Torch is working as intended: Grimoire of Gaia Mobs cannot spawn naturally in the working volume of a Mega Torch.

/closed
