### ISSUE TITLE
Quark compatability - Foxhound still spawning

### ISSUE THREAD

**Issue by rickspencer** [Xalcon/TorchMaster#130]
Looks like the Foxhound from Quark is still spawning in the nether...
I've not tested with any other Quark mobs...

**Comment by rickspencer** [comment]
Sorry, we are using v2.11 - I just saw that this was fixed 11 days ago... I'm assuming latest version 2.15 has the fix?

**Comment by Xalcon** [comment]
This was fixed in 2.2.0, latest version is 2.2.1
