### ISSUE TITLE
High CPU-Usage and Exception-Crash

### ISSUE THREAD

**Issue by Andor79** [Xalcon/TorchMaster#132]
When the Invisible Light Block from the Feral Flare Lantern seems to be near or in flowing liquid (water/lava) my server performance keeps dropping and when the chunk is loaded the server often crashes,

MC-Version: 1.16.1
Forge: 32.0.99
Mod:  2.3.1 alpha

Error-Log:  [https://pastebin.com/XAG0ZbqT](url)

**Comment by Xalcon** [comment]
I'm having trouble replicating the issue with just torchmaster. Are there any vines around the lantern? The crash indicates some issue with vines.

**Comment by Xalcon** [comment]
I don't know what exactly the issue could be. I'm unable to replicate this locally but considering I got 2 reports within hours of each other for the same problem, there might be something more behind it. This is pretty much a shot in the dark, but it might help. I've removed the invisible block from the mod and replaced it with a light emitting air block that uses the actual AirBlock class from minecraft. Please update to Torchmaster 2.3.2-alpha for MC 1.16.1 and let me know if the issue persists.

**Comment by Andor79** [comment]
Fix seems to work! No longer crashing. Will try to test it intensely under different conditions.

Many thanks for the fast hotfix !!!

**Comment by Xalcon** [comment]
I'm happy to hear this is working for you. I'll be waiting for a response in #133 from @BlazingPL if the fix also worked for them, but if I don't hear anything from you guys, I'll assume it's fixed :)

**Comment by Xalcon** [comment]
Closing this since I got the confirmation this was fixed :) If there is still anything that looks like a similar issue, please open a NEW issue. Thanks!
