### ISSUE TITLE
Version 1.8.2 for MC 1.12.2

### ISSUE THREAD

**Issue by xJon** [Xalcon/TorchMaster#134]
Hi,
Is this build - https://www.curseforge.com/minecraft/mc-mods/torchmaster/files/3017979 actually version `1.8.2`?

**Comment by Xalcon** [comment]
~No, this is 1.8.1.82. There is no version 1.8.2.
1.12 uses the scheme `MAJOR.MINOR.PATCH.BUILDNUMBER`
With MC 1.13 i removed the buildnumber from from the version string as it didn't provide any additional information. Every release I do will always increase either of the 3 version numbers, so there is no point in having the buildnumber.~

Whoops, well - yes, it looks like this should've been 1.8.2.82. The version 1.12 actually builds automatically and I always forget to update the version number. I guess I changed the version number and did the commit but selected the wrong file to release. The Dreadlamp Visual Bugfix should still be in this version though.

**Comment by xJon** [comment]
No worries, I wondered because the file in CurseForge also didn't have the proper changelog.
I've marked the update in my Technic Solder as `1.8.2` (I also marked the previous ones without the buildnumber as I saw it was pointless)
