### ISSUE TITLE
Slime farms

### ISSUE THREAD

**Issue by keremlov** [Xalcon/TorchMaster#135]
Hello, I use feral flare lanterns to prevent mob spawning around my slime Farm and in my slime Farm. However I get way less slime spawn like one or two per hour. Do you think its because the transparent light sources of feral flare is affecting the spawn rate? Cause mobs can't spawn on torches or leaves I thought this might be the same thing?

**Comment by Xalcon** [comment]
Sorry for the late response.
This depends on the version you are playing. In MC 1.16 the lights placed by the feral flare lantern are actually air blocks that just emit light, so they should not be blocking any spawn attempts like leaves. In older versions I'm using a custom block that may have an effect on spawning.

**Comment by keremlov** [comment]
Thank you! That's very helpful
