### ISSUE TITLE
Feral Flare Lantern

### ISSUE THREAD

**Issue by cc3768** [Xalcon/TorchMaster#136]
Placing 6 near each other causes a server to lock up
With no crash or logs just a full halt on the server end

**Comment by cc3768** [comment]
https://drive.google.com/drive/folders/102ZLM8dtvT0oT8D56B6FNi9ADWqe1YXI?usp=sharing

**Comment by Xalcon** [comment]
Can you elaborate on this a bit? Which version of the mod are you using?

**Comment by Xalcon** [comment]
None of the supported versions show said behavior. I placed a ton of lamps on the same spot without visible impact on the TPS.
I'll need more information on this, i can't fix a bug that I'm unable to replicate :/

![image](https://user-images.githubusercontent.com/5042450/92143187-2e7eb080-ee15-11ea-8ae9-2aece9374ec1.png)

![image](https://user-images.githubusercontent.com/5042450/92142801-a7c9d380-ee14-11ea-83cb-fd272d3394ca.png)

![image](https://user-images.githubusercontent.com/5042450/92143430-92a17480-ee15-11ea-8348-0a0a0dd36b34.png)

**Comment by NielsPilgaard** [comment]
I believe it is using `torchmaster-2.3.2-alpha` and `Forge-1.16.1-32.0.108`, modpack `Enigmatica 6 0.2.14`
I have not been able to reproduce the issue locally either.

**Comment by Xalcon** [comment]
I'll close this due to inactivity. If someone is able to replicate the issue, please let me know.
