### ISSUE TITLE
[1.16.3] Terrain Lighter Missing?

### ISSUE THREAD

**Issue by seanimusprime** [Xalcon/TorchMaster#138]
Is the terrain lighter removed from 1.16.3 permanently or is it something that you're working on to get implemented? I'm just wondering because that was one of my favorite things from previous versions that I've played with.

**Comment by Xalcon** [comment]
I took the 1.13 (or was it 1.14?) update to completly rewrite the mod from scratch. Back then there weren't many resources around to do GUIs, so I just didn't bother implementing it - i wasnt even sure if people do use the terrain lighter.

**Comment by seanimusprime** [comment]
I can't speak for others but I definitely used it, especially in the Skyfactory 4 modpack playing on the lost cities world type. It was almost a necessity.

**Comment by xannor** [comment]
+2p. I never got to use this but to me its description feels like an early game safe-zone generator so maybe it doesn't need a gui but instead have it have the visuals of a furnace. without fuel it is dim, while burning fuel it is brighter, and a simple right click to add fuel (and maybe some sided-ness for hoppers/etc.) maybe also only have it accept one item at a time so you don't have to guess how much fuel is in it.

**Comment by Xalcon** [comment]
I will not implement the terrain lighter again. The Feral Flare Lantern is a somewhat suitable alternative and with mobs only spawning at light level 0 now, the block loses its usefulness.
