### ISSUE TITLE
[suggestion] dyable torches

### ISSUE THREAD

**Issue by Deragonis** [Xalcon/TorchMaster#148]
the lanterns and torches are great but when they don't fit the design or idea of the base then they are normally hidden begins walls, I would like to implement them in builds instead of hiding them so I feel adding a way to dye the mega torch, feral flare lantern, etc, would be great, minor add on suggestions a way to change the colour of the fire or use different base designs, like birth wood or blackstone for them would also be helpful for builds

**Comment by Xalcon** [comment]
Generally this is an interesting idea but customizable torches would be a bit out of scope of this mod. I do have an idea on how to accomplish this, so it is not fully off the table - but no promises.
