### ISSUE TITLE
Husks spawn are not bein blocked by Mega Torch

### ISSUE THREAD

**Issue by DanJ4n** [Xalcon/TorchMaster#157]
Hi, as the title states Zombie Husks spawn are not being blocked by the mega torch resulting in surrounding areas being filled with them.

Minecraft version 1.16.5

The biome I've encountered this issue is "dunes" from mod atmospheric.

**Comment by Xalcon** [comment]
I'm unable to replicate the bug.
 * Forge 1.16.5-36.2.2
 * Torchmaster 2.3.7
 * Abnormals Core 3.2.0
 * Atmospheric 3.1.0

I've created a new "single biome" world with the "dune" biome. There were no mobs spawning inside the radius of my torch, neither husks nor any other type of aggressive entity.

Are you able to replicate this with just Torchmaster and Atmosphere? This sounds like some other mod doing something bad or unexpected here.
