### ISSUE TITLE
Crash w/ BiblioCraft Mod

### ISSUE THREAD

**Issue by WenXin20** [Xalcon/TorchMaster#16]
Forge 2254
[BiblioCraft ](https://minecraft.curseforge.com/projects/bibliocraft/files/2378365)v2.2.1
I got a crash after adding "bibliocraft:LanternGold" to the Terrain Lighter Torches config list. The crash happens after putting the lantern into the terrain lighter block.
[Crash Report ](https://pastebin.com/xUUrKfDJ)

**Comment by Xalcon** [comment]
I was able to replicate the issue. I will try to provide a fix in the next few hours. Thanks for the report.

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by Xalcon** [comment]
I've submitted v1.2.2 for 1.10.2 to curseforge. Should be available in a few minutes.
A fix for 1.11.2 will follow later today or tomorrow.
