### ISSUE TITLE
[1.16.5 Datapack] Custom Recipes not working!

### ISSUE THREAD

**Issue by BigMartin58** [Xalcon/TorchMaster#160]
I have tried multiple custom recipes for the megatorch and none are working. It just doesn't change. Every custom recipe I've made for other mods will load after typing /reload but specifically for the megatorch, it doesn't. I know there's nothing wrong with my recipe because it's a direct copy-paste of the original with my alternate ingredients.

**Edit:** Smithing Recipes do work.
**Edit2:** I discovered that Torchmaster gets loaded last, even after datapacks, so I'm assuming it overwrites the datapack recipe. It still should be loaded last for the aggressiveSpawn check but before datapacks. 
**Edit3:** Deleting the recipe in the .jar file fixes it, but it's only a workaround. The issue still needs to be fixed.

**Comment by Xalcon** [comment]
This should be fixed with the switch to deferred registries (1.19+)
A backport is currently not planned.
