### ISSUE TITLE
[1.16.5] InControl mobs aren't blocked by Mega Torch

### ISSUE THREAD

**Issue by TqLxQuanZ** [Xalcon/TorchMaster#161]
Currently I am looking with a mod that provides block to prevent enemy spawn within radius and I came across this one, but found out that it doesn't work with InControl's spawn rules. Basically, I disabled the vanilla zombies and zombie villagers, only allow the one from Incontrol spawns, but somehow they bypass the megatorch's check and spawn regardless.
The norestriction is needed as I need them to spawn under daylight, or any light source regardless, but able to be blocked by a specific block.
Here is the simple rule I made:
spawner.json
```
 {   
        "mob": [
            "minecraft:zombie",
            "minecraft:zombie_villager"],
        "persecond": 5,
        "attempts": 10,
        "amount": {
        "minimum": 10,
        "maximum": 25
        },
        "conditions": {
            "dimension": "minecraft:overworld",
            "mindist": 30,
            "maxdist": 120,
            "norestrictions": true,
            "minheight": 1,
            "maxheight": 256,
            "maxhostile": 150
        }
    }
```
    
   spawn.json
```
       {
        "mob": [
            "minecraft:zombie",
            "minecraft:zombie_villager",
        ],
        "incontrol": true,
        "result": "allow"
    },
    {
        "mob": [
            "minecraft:zombie",
            "minecraft:zombie_villager",
        ],
        "result": "deny"
    },
```

**Comment by Xalcon** [comment]
Which version are you using? I recall having issues with incontrol in the past. The most recent version of torchmaster may have re-introduced the issue.

**Comment by TqLxQuanZ** [comment]
> Which version are you using? I recall having issues with incontrol in the past. The most recent version of torchmaster may have re-introduced the issue.

My apologies for not quoting version, the InControl version I am using is InControl 1.16-5.2.0, while Torchmaster is 
torchmaster-2.3.8. Let me know if you need more info.

**Comment by Xalcon** [comment]
Hm, the changes I'm talking about were introduced in version 2.3.9. can you try updating?

**Comment by TqLxQuanZ** [comment]
> Hm, the changes I'm talking about were introduced in version 2.3.9. can you try updating?

I don't see 2.3.9 in curseforge, only 2.3.8 August 21, 2021.

**Comment by Xalcon** [comment]
Nevermind then, I mixed up some version numbers. I'll look into the issue but if you find the time, could you test with 2.3.7? I was hoping I don't need to add a workaround to my 2.3.8 changes but it seems there are still mods that do ignore spawn event results.

**Comment by TqLxQuanZ** [comment]
> Nevermind then, I mixed up some version numbers. I'll look into the issue but if you find the time, could you test with 2.3.7? I was hoping I don't need to add a workaround to my 2.3.8 changes but it seems there are still mods that do ignore spawn event results.

Alright, I'll test with that version, I'll let you know in a bit.

**Comment by TqLxQuanZ** [comment]
2.3.7 has the same issue, in torchmaster config I set aggressiveSpawnCheck to true as well, blockOnlyNaturalSpawn = false. Same InControl version as above mentioned.

**Comment by Xalcon** [comment]
If it doesn't work in 2.3.7 either, then it is most likely nothing I can easily fix. I don't know what incontrol is doing but it sounds like they are not utilizing the proper spawn events torchmaster relies on.

**Comment by TqLxQuanZ** [comment]
> If it doesn't work in 2.3.7 either, then it is most likely nothing I can easily fix. I don't know what incontrol is doing but it sounds like they are not utilizing the proper spawn events torchmaster relies on.

I guess it can't be helped, since InControl seems to have its own spawn events.

**Comment by brisingraerowing** [comment]
I'm noticing this behavior in one of my packs, but I don't have InControl. I think there's a mod that is breaking spawn events in a way that prevents Torchmaster from working. I'm currently trying to isolate what mod that is.

**Comment by wendictive** [comment]
still an issue
