### ISSUE TITLE
Feral Flare Lantern crafting doesn´t work (version 1.16.5, torchmaster-2.3.8) 

### ISSUE THREAD

**Issue by MonkeyDSeni** [Xalcon/TorchMaster#164]
I´ve tried to craft the feral flare lantern both on creative and survival mode as i´ve seen it is done, and it doesn´t let me craft it.
I´ve seen it is done with 2 golden lingots, 2 glass blocks and a glovestone block. It doesn´t work.
Any idea why? or how i could fix it?
Thx.

**Comment by Xalcon** [comment]
Its not a glowstone block. Just the dust, atleast by default. Modpacks obviously can have different recipes if they like.
![image](https://user-images.githubusercontent.com/5042450/136827842-d13d8476-83aa-4064-8a1d-80cb18ec3f82.png)

**Comment by MonkeyDSeni** [comment]
thx, i tried that way a few days ago and didnt work, but it is working now, thank you very much.
