### ISSUE TITLE
[1.16.5] Mega torch not working in FTB Ocean Block

### ISSUE THREAD

**Issue by atanil** [Xalcon/TorchMaster#165]
Modpack: FTB Ocean Block v.1.1.0
Torchmaster v.2.3.8
megaTorchRadius = 64

I placed Mega torch in the middle of my base, but hostile mobs are still spawning around.
(radius of that cobble wall is 65)
![2021-10-17_16 55 56](https://user-images.githubusercontent.com/17858496/137634965-c448886f-ff94-4e87-a868-0ab389d56657.png)

**Comment by Xalcon** [comment]
I'm not sure what to do here. Torchmaster works fine - in isolation and even with most mods side by side. If there are mobs spawning, then its generally an issue with the mod spawning the mobs.

**Comment by atanil** [comment]
I think I found the culprit. When I removed WYML I saw no mobs spawning around mega torch.

**Comment by Xalcon** [comment]
That sounds odd, but maybe the mod is modifying the game and removing important features to allow for reduced lag. Not something I can fix on torchmasters side. I'll close this for now.
