### ISSUE TITLE
Question about torch master for 1.12.2

### ISSUE THREAD

**Issue by Fireworkstars46** [Xalcon/TorchMaster#166]
Is there a way to customize the block radius for torch master?

**Comment by Xalcon** [comment]
check the configuration file for torchmaster. It allows you to change the range for all 3 types of lights in torchmaster.

**Comment by Fireworkstars46** [comment]
So I can't change the radius in game without the config?

**Comment by Xalcon** [comment]
No, there is no ingame configuration menu as of now. I will look into that.
