### ISSUE TITLE
feature Allow Wandering Trader spawn

### ISSUE THREAD

**Issue by ArkavianX** [Xalcon/TorchMaster#168]
i've noticed wandering traders do not spawn with dreadlamp placed.

**Comment by Xalcon** [comment]
I would call that intended behavior. The trader is a passive entity and the lamp is supposed to block passive entities.

If you want to remove the trader from the list, you can add "whitelist entry" to the `dreadLampEntityBlockListOverrides` in the torchmaster.toml:
```
#Same as the mega torch block list override, just for the dread lamp
#Block squid: +minecraft:squid
#Allow pigs: -minecraft:pig
dreadLampEntityBlockListOverrides = [
    "-minecraft:wandering_trader"
]
```

//Edit:
I didn't realize this was a feature request. My bad. But the feature is already there :) Does it solve your problem?

**Comment by ArkavianX** [comment]
hmm k will try that
