### ISSUE TITLE
[1.12.2] Feral Flare lanterns causing massive chunkloading.

### ISSUE THREAD

**Issue by ProsperCraft** [Xalcon/TorchMaster#169]
torchmaster_1.12.2-1.8.4.84

Modpack- TownCraft ONE

Process to discover- 

I was troubleshooting a TPS issue and used the sampler mod to /sampler loads show
Which then showed a continuous stream of chunks being loaded from Feral Flare lanterns.

There were only two players online, and we were in the same location and not moving.

After not too long my server log was 58 megs and overpowered Gist, so I just pasted a small portion of it.

https://gist.github.com/ProsperCraft/f3058402df90359483fffc34b27dfe2e

**Comment by Xalcon** [comment]
Hm, interesting. Is the feral lantern by chance chunk loaded itself? What size is it configured to illuminate?

**Comment by Xalcon** [comment]
I've uploaded the new version 1.8.5.0, which you can get from curseforge or via github:
https://www.curseforge.com/minecraft/mc-mods/torchmaster/files/3529742
https://github.com/Xalcon/TorchMaster/releases/tag/refs%2Fheads%2Fmc1.12-1.8.5.0

Can you check if this fixes your issue?

**Comment by ProsperCraft** [comment]
Looks like you totally nailed it! Thank you so much for the fast fix, it is very much appreciated!
