### ISSUE TITLE
[TorchMaster 1.3.1.33] Crash upon startup

### ISSUE THREAD

**Issue by shortybsd** [Xalcon/TorchMaster#17]
MineCraft 1.11.2
Forge 2284
TorchMaster v1.3.1.33

java.lang.ClassNotFoundException: net.xalcon.torchmaster.server.CommonProxy crash upon server startup.

In your mod you are missing CommonProxy.class, EventHandlerServer.class, TorchRegistry$TorchLocation.class and TorchRegistry.class. In your new version you have 2 new files Proxy.class and ModTileEntities.class.
<a href="https://pastebin.com/StisYX4r" target="_blank">Detailed Error</a>

**Comment by Xalcon** [comment]
Can you please re-download the jar from curseforge for version 1.3.1.33? I've just downloaded that exact file from curseforge and my 1.11.2 instance fires up just fine.
Maybe even try removing some of the other installed mods to rule any weired interaction out.

If you find issues with any of the other mods, please report back here, so I can take a look at it.

As of now, it doesnt look like an issue with TorchMaster itself.

**Comment by TehNut** [comment]
```
TehNut [Bowel Movement | Weeb] - Today at 11:51 PM
you don't have a server package
You have a common package that has CommonProxy init
https://github.com/Xalcon/TorchMaster/blob/master/src/main/java/net/xalcon/torchmaster/TorchMasterMod.java#L30

xalcon [TorchMaster] - Today at 11:52 PM
o___o

TehNut [Bowel Movement | Weeb] - Today at 11:52 PM
Yo'ure telling it to look for server

xalcon [TorchMaster] - Today at 11:52 PM
how didnt i notice that
oh shit, i know

TehNut [Bowel Movement | Weeb] - Today at 11:52 PM
And you'll only get that crash on a dedicated server since it's the server proxy
```

**Comment by Xalcon** [comment]
I have a fixed version up, its currently being reviewed by curseforge.
Sorry for the inconvenience.

**Comment by shortybsd** [comment]
hehe all good man, thanks for the fast update!
