### ISSUE TITLE
[1.17.1] Cannot open GUI on Feral Flare Torch.

### ISSUE THREAD

**Issue by Kurunoa** [Xalcon/TorchMaster#170]
Using All The Mods 7 modpack, torchmaster-3.0.1-beta.jar.

Rightclicking the Feral Flare Torch does nothing.

Need to do so to disable line-of-sight.

**Comment by Xalcon** [comment]
Not really a bug, just not implemented. I'm planning to revisit a few of the blocks with the 1.18 (and potentially backport these features to 1.17 if needed).
