### ISSUE TITLE
[Request] Block Atum Patrols with Torchmaster Mega Torch

### ISSUE THREAD

**Issue by NielsPilgaard** [Xalcon/TorchMaster#173]
In the mod [Atum](https://www.curseforge.com/minecraft/mc-mods/atum) patrols spawn frequently around the player. 
Allowing the Mega Torch from [Torchmaster](https://www.curseforge.com/minecraft/mc-mods/torchmaster) to block them would be lovely for when building in the dimension.

I'm unsure which mod would need to implement this, so I'm posting it in both trackers 😄 

Atum issue: https://github.com/TeamMetallurgy/Atum2/issues/377

**Comment by Xalcon** [comment]
Not sure if this is still relevant. Village Sieges should be blocked as of 18.x and in the future, additional "non-compliant" spawns should be blockable via the upcoming asynchronous entity blocking feature, #187
