### ISSUE TITLE
[1.18] Blocks have no assigned tool

### ISSUE THREAD

**Issue by TheRealWormbo** [Xalcon/TorchMaster#180]
Using version 18.0.3-beta, none of the placeable blocks have tools assigned. I seem to remember from older versions that the Mega Torch could be mined faster using an axe and the Dread Lamp and Feral Flare Lantern using a pickaxe.

**Comment by Xalcon** [comment]
fixed in v18.0.4

**Comment by TheRealWormbo** [comment]
Wow, that was quick! I was curious how this is done, and had a look at the change set. It seems a random "7" snug into the JSON file for the megatorch somehow, which you might want to check.

**Comment by Xalcon** [comment]
That is indeed wrong, fixed in 18.0.5
