### ISSUE TITLE
[1.18] Placing/breaking sounds for Mega Torch and Feral Flare Lantern seem wrong

### ISSUE THREAD

**Issue by TheRealWormbo** [Xalcon/TorchMaster#182]
When placing or breaking a Mega Torch or Feral Flare Lantern, the sounds for placing or breaking stone-like blocks play.

Considering the amount of wood in the Mega Torch and its look, it seems reasonable to expect it to make sounds similar to a wooden block. Similarly, the crafting recipe for the Feral Flare Lantern contains glass, gold and glowstone, and the result looks somewhat similar to the vanilla lantern. It might make sense to use the same placing and breaking sounds as that one.

**Comment by Xalcon** [comment]
I've never really put too much considerations into what sounds a block should make for any sort of action.

fixed in v18.0.4
