### ISSUE TITLE
[Request] Datapack entry for burnout item use mechanic

### ISSUE THREAD

**Issue by KittenRaee** [Xalcon/TorchMaster#185]
Since modding and making modpacks via datapacks are much more common, there should be option to create datapack entry for [Item use mechanic](https://github.com/Xalcon/TorchMaster/wiki/Torch-Burnout#item-use-mechanic) instead of being forced to use CraftTweaker.

**Comment by Xalcon** [comment]
Torch Burnout is not implemented at the moment, the wiki entry is from a time where datapacks were not a thing yet. I didn't bother re-implementing the burnout mechanic since nobody ever seem to miss it. I'll keep datapacks in mind though for features that would profit from it.

**Comment by FoxyFox909** [comment]
Damn, I was actually hoping to use the burnout mechanic in my 1.18.2 modpack lol!
