### ISSUE TITLE
HostileMobSpawning

### ISSUE THREAD

**Issue by Wolfy2004** [Xalcon/TorchMaster#188]
Hello mod maker,

I have recently started playing on a server with friends with the pack TNP Limitless 5. I have recently discovered a thing with the Mega Torch.. There is ONE specific mob that spawns (well actually 2 but the other one only spawns in the water). I am talking about the Lobber Zombie from the modpack Earth Mobs mod. If its possible could u code in that this mob doesnt spawn? It could cause trouble if we're trying to make a village and this mob spawns in it all of the sudden..

Best regards,
Wolfy

**Comment by Xalcon** [comment]
It depends on how the mob is spawned and which mod is doing it. Generally I don't do much mod specific support because it tends to break after a few patches, but I have an Idea how this can be solved via a generic system.

**Comment by Xalcon** [comment]
This will be possible via the Asynchronous Entity Blocking, tracked by #187
