### ISSUE TITLE
[1.19] Placing feral flare lantern crashes the client

### ISSUE THREAD

**Issue by Saereth** [Xalcon/TorchMaster#189]
Crashlog:
[crash-2022-06-12_08.31.17-client.txt](https://github.com/Xalcon/TorchMaster/files/8886192/crash-2022-06-12_08.31.17-client.txt)

**Comment by Xalcon** [comment]
thanks for reporting, one of those typical 1 line issues. Not sure how I missed that. fixed in 19.0.1-beta
