### ISSUE TITLE
[Request] Change formatting on curseforge page

### ISSUE THREAD

**Issue by Kingmiami** [Xalcon/TorchMaster#190]
This is the current text on the CF page for Torchmaster, as of me writing this post:

| Version | Support | End-Of-Life | | - | - | - | | 1.19 | ✅ | atleast 2022-12-31 | | 1.18 | ✅ | 2023-12-31 | | 1.17 | 🪦 | 2022-06-01 | | 1.16 | ✅ | 2022-12-31 | | 1.15 | 🪦 | 2021-12-31 | | 1.14 | 🪦 | 2021-12-31 | | 1.13 | 🪦 | 2021-12-31 | | 1.12 | 🪦 | 2021-12-31 | | 1.11 | 🪦 | 2021-12-31 | | 1.10 | 🪦 | 2021-12-31 |

I really like the concept here, but I feel like the formatting could be a bit better. I know how silly or trivial this may be, but I'm personally a stickler for that stuff, and it would make this easier to read. This is my proposal:

| Version | Support | End-Of-Life |

| 1.xx  | n/a | XXXX-XX-XX |
| 1.19 | ✅ | at least 2022-12-31 | 
| 1.18 | ✅ | 2023-12-31 | 
| 1.17 | 🪦 | 2022-06-01 | 
| 1.16 | ✅ | 2022-12-31 | 
| 1.15 | 🪦 | 2021-12-31 | 
| 1.14 | 🪦 | 2021-12-31 | 
| 1.13 | 🪦 | 2021-12-31 | 
| 1.12 | 🪦 | 2021-12-31 | 
| 1.11 | 🪦 | 2021-12-31 | 
| 1.10 | 🪦 | 2021-12-31 |

Please consider changing the description to this. Thank you.

**Comment by Xalcon** [comment]
Funnily enough, the way you want this to look like is exactly how i typed it - curseforge is just a broken mess that can't render markdown properly. ~~I'll need to rewrite the full description using the WYSIWYG editor.~~
I copied the text into the other editor 1:1 and atleast its readable now. Would be nice if they supported tables.
