### ISSUE TITLE
[1.19.2] Server Side Crash (at net.xalcon.torchmaster.common.logic.entityblocking.megatorch) (Watchdog)

### ISSUE THREAD

**Issue by Gbergz** [Xalcon/TorchMaster#195]
Title ^

Server dies after starting, hitting the server watchdog limit at 1000 secs.

Minecraft: 1.19.2
Forge: 40.1.84
Torchmaster: 18.1.0

Crash-Report: https://gist.github.com/Gbergz/d501687f52c614afa3ea40194aec6cb8

**Comment by Xalcon** [comment]
I dare to say this is not a torchmaster issue.
The last reference by torchmaster points to https://github.com/Xalcon/TorchMaster/blob/3a49afa22732752a89369a5be81d56a5bf941126/src/main/java/net/xalcon/torchmaster/common/logic/entityblocking/megatorch/MegatorchEntityBlockingLight.java#L50-L54
But afterwards, there are a bunch of other calls to several mixins. To me, this looks like an issue with Smooth Chunks.
The code in question is so lean, it could run for thousands of torches per tick without a visible impact on the tick rate, so this doesnt look like a general performance issue but rather a mod locking up.
