### ISSUE TITLE
spriggan spawns not being stopped by mega torch

### ISSUE THREAD

**Issue by deadlywolf301** [Xalcon/TorchMaster#199]
been playing in 1.12.2 and just added the torchmaster mod to help with my spriggan problem cause I s**t you not in a matter of about 1-2 minutes over twenty spawn in my mystical crop farm, granted its a pretty big farm but, trying to do any work while being constantly bombarded by these things is not happening, now I know that this version has basically no support any more but other than tuning down the spawn frequency I cant stop them. ps. I have like 16 placed around my farm and they spawn in the radius. if you need more proof I can make a video and post it on my YT channel and link it to you. reason for spawn is when my farming station from ender io harvests my crops they spawn.
forge version: 14.23.5.2860
torchmaster version: 1.8.5.0
lycanites mobs version: 2.0.8.7
mystical agriculture version: 1.7.5
ender io version: 5.3.70

**Comment by Xalcon** [comment]
There is not much I can do. If a mod spawns a mob without using the event system, I can't reasonably block it, especially in such an old version as 1.12
