### ISSUE TITLE
cuaght on openeye when on server player was moving mega torch in inv causing client to crash

### ISSUE THREAD

**Issue by SDUBZ** [Xalcon/TorchMaster#20]
torchmaster: torchmaster_1.11.2-1.3.2.35.jar
forge:1.11.2-2296
crash: https://openeye.openmods.info/crashes/a99a6f7fbec5904719491f84f7555c6c

might be fixed by now thought id let you know

**Comment by Xalcon** [comment]
this bug is fixed as of version 1.3.3.37, see #18
