### ISSUE TITLE
1.19.3 Support

### ISSUE THREAD

**Issue by TheseusBlue** [Xalcon/TorchMaster#200]
Just a friendly request, as I don't know how trivial it would be, but currently the latest release of Torchmaster is not working for me with 1.19.3 (Forge 44.1.0).

**Comment by Xalcon** [comment]
Sorry for the delay, I'll look into it - but generally, i dont think it will take that long for minor version bumps

**Comment by Xalcon** [comment]
Update is available on curseforge. Modrinth will follow soon-ish, my github action is broken.
