### ISSUE TITLE
1.19 Server watchdog

### ISSUE THREAD

**Issue by Atla5De5troyer** [Xalcon/TorchMaster#201]
Looks like torchmaster is causing the server to hang, not sure what the actual issue. Thought I'd ask you see if you know what the issue could be?

https://mclo.gs/v1N6mHc

**Comment by Xalcon** [comment]
I think I've seen this one before. Back then I came to the conclusion this is not a torchmaster issue.
From the log you can clearly see that the last call to/from torchmaster is:
https://github.com/Xalcon/TorchMaster/blob/b9adf648092c436cde0e0e39dc72027ff60a8210/src/main/java/net/xalcon/torchmaster/common/logic/entityblocking/megatorch/MegatorchEntityBlockingLight.java#L51-L55

This in itself can't lock up the server. According to the log, this causes some class loading and access transformer magic with kubejs/lootr being involved after torchmaster. Generally, using `Level.isLoaded()` and `level.getBlockState()` should not cause any class loading at that point - to me this looks like another mod is messing things up.
