### ISSUE TITLE
Feral Flare Lanterns cause Shade in some chunks - Possibly not clearing light sources

### ISSUE THREAD

**Issue by zeocrash** [Xalcon/TorchMaster#202]
There is a chunk of my base that acts as though it's in darkness/shade even though it's not, As seen In this picture. 
![2023-02-14_15 35 29](https://user-images.githubusercontent.com/55654921/218794440-04e7d308-68dc-4ddc-b8d3-04c044a6faec.png)

I believe this is partly caused by an existing Minecraft issue ([Light sources spontaneously not working in some chunks](https://bugs.mojang.com/browse/MC-142134?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true) ) but Is made worse by Feral Flare Lanterns.

### Modpack
All the Mods 8 V1.0.10

### Issue
I have been using Feral Flare Lanterns to light my base. Recently I noticed that the front chunk of my base  was permanently in shade, despite having a clear view of the sky. I also Noticed strange Lighting behaviour inside my base
![2023-02-14_15 43 44](https://user-images.githubusercontent.com/55654921/218796386-b13d6331-28af-4bb8-81a4-3e74402ccb26.png)

![2023-02-14_15 43 31](https://user-images.githubusercontent.com/55654921/218796268-3fa07db5-0bbb-433a-b165-cd4455b6aeb0.png)
There Is a Feral Flare lantern clearly Visible in the first image but there is a strange Light and dark pattern produced on the walls.

I removed the Feral Flare Lanterns and some of the dark areas went back to normal behaviour, but not all of them. The Image below shows the outside area. At this point there is not a single Feral Flare Lantern remaining in my base.
![2023-02-14_16 23 49](https://user-images.githubusercontent.com/55654921/218796975-0afa1af5-59b0-4855-886b-9cf736bad380.png)

### What I think the cause of the problem is
I think the cause of the problem (Aside from the Minecraft issue mentioned above) is that feral lanterns don't properly clean up their light sources when broken. The Image below shows a room that has had all feral lanterns removed from it (about 15 mins before the picture was taken) and has no other light sources (and we're deep underground). 
![2023-02-14_16 30 13](https://user-images.githubusercontent.com/55654921/218798866-16f0ad23-554b-42fa-bf1e-2d75a0cdf96c.png)

As you can see there is a very distinct light patch, which I believe is a light source that was placed by a feral flare lantern. I believe that this combined with the Minecraft light source bug mentioned above is what's causing this issue.

I think what happens is that the Feral Flare lantern places down lots of light sources. The Minecraft lighting bug causes the light sources to become not functional. Breaking the Feral Flare lantern doesn't remove the non functional light sources and this causes the area to remain darkened. 
 
### Attempted Solutions

I used an RFtools builder to fill the entire outside chunk from the ground level to max build height (Y320) and then removed it all. This fixed the issue temporarily but the issue returned (Presumably due to the Feral Lanterns in my base placing more light sources which then became non functional. 

I removed all feral flare lanterns in my base. This fixed the issue. I then re added the feral flare lanterns. When I logged back into the game today the Issue had returned. Removing all Feral flare lanterns a second time no longer fixed the issue.

**Comment by zeocrash** [comment]
It occurs to me that If it's too much of a ball-ache for feral flare lanterns to reliably keep track of the light sources they spawn, a workable workaround would be to add a tool to torchmaster to remove all Feral lantern light sources in the vicinity/chunk

**Comment by Xalcon** [comment]
Its a bit odd to see these kind of issues, but from the get go I tried to avoid lights to stay around - but in case there are some left after breaking the lantern, you should be able to use the Frozen Pearl to remove any lingering lights - if there are any.

**Comment by zeocrash** [comment]
Thanks. I'll use the Frozen Pearl. 
I was wondering if the cause of the lingering lights was related to chunk loading I.E. if a lantern in a chunk loaded chunk spawns light sources in a nearby chunk that's not chunk loaded, whether this might cause issues later on when it tries to remove entities. 
I did take a look at the code in the repo and the code to clean up light sources looks ok (although I'm not that familiar with the internal workings of Minecraft servers).

**Comment by Xalcon** [comment]
Generally, its supprising to see this lighting error in the first place. The only thing I do is to spawn blocks that emit light but have no model. They don't differ from a simple minecraft torch in any way other than the fact they are "invisible".

Chunkloading has been an odd thing in minecraft since the beginning, so it might be related.
After some closer investigation, I may have found a call that may cause non-intentional chunkloading. I've created a fix, please let me know if this has any effect on your issue. Version 19.2.2 should be available in the next few minutes on curseforge and on the github release page.

**Comment by Sebastrn** [comment]
If anyone is facing this issue, I got rid of it by installing the Starlight mod in my server.
