### ISSUE TITLE
Bugged light sources from the feral flare lantern 

### ISSUE THREAD

**Issue by Sunekaer** [Xalcon/TorchMaster#207]
1.18.2

### Describe the bug

Light sources from the feral flare lantern won't disappear when you brake the lantern with RFTools Builder

### Steps to reproduce

1. Place a feral flare lantern
2. Break it using RFTools Builder
3. Light sources stay

### Expected behaviour

Light sources to disappear

### Screenshots

![image](https://user-images.githubusercontent.com/60789741/207061884-89d4e689-41e3-4e16-bda5-11fdf44048e5.png)

**Comment by Xalcon** [comment]
Thanks for reporting this. I guess I'm not checking for all block breaking/removal actions. I'll look into it

**Comment by Xalcon** [comment]
Fixed (hopefully) in
v18.2.0 for MC 1.18.2
v19.2.90 for MC 1.19.2
v19.4.0 for MC 1.19.4
