### ISSUE TITLE
mega torch does not work on apotheosis bosses 

### ISSUE THREAD

**Issue by GPucchi** [Xalcon/TorchMaster#208]
saw that you fixed it a couple years ago so that mega torch works on apotheosis bosses but now it doesn't work. playing on ATM 8 1.0.17 tried to find out why it doesn't work and all i got was that apotheosis is now using SpecialSpawn

**Comment by Xalcon** [comment]
Yes, this is a known issue with mods that explicitly allow spawns rather than leaving the event result as is. You can try enabling the `aggressiveSpawnChecks` in the config, it may help.

**Comment by GPucchi** [comment]
thanks that worked. i was testing it for the past hour and nothing seems wrong but can i ask why aggressiveSpawnChecks is disabled by default?

**Comment by Xalcon** [comment]
I like to be the least intrussive possible by default. Generally, the event supports 3 different results.
`Deny` = The spawn will be blocked
`Allow`= Explicitly allow the spawn. Can only be set by a mod.
`Default` = This is the default, generally the same as `allow` but indicates that no other mod has changed it yet

This means, if the result is set to `allow`, another mod explicitly requested this spawn to go through. Torchmaster is running pretty late in the Event Queue, which means other mods are able to change this result before hand. The setting just makes it so torchmaster ignores the requested result from other mods, potentially breaking stuff - or in this case, getting things to work differently to how the mod author of the blocked mob intendend it to work.
