### ISSUE TITLE
[Bug]Compatibility with Mod [In Control!]

### ISSUE THREAD

**Issue by LFMaozi** [Xalcon/TorchMaster#209]
**Description**
Mega Torch won’t correctly override and stop the spawn of mod [In Control!] when spawn condition is introduced (config aggressiveSpawnChecks = true).

Mod [In Control!]: https://www.curseforge.com/minecraft/mc-mods/in-control

[In Control!] is a a simple mod that gives you full control on where mobs are allowed to spawn. It is based on a rule system. 
Basicly you add spawns in _\config\incontrol\spawner.json_ and set spawn conditions in _\config\incontrol\spawn.json_ . 

Mega Torch functions normally with _spawner_, but, once a _spawn_ conditions is introduced, the Mega Torch won't stop the spawn anymore.

Here's my testing code which spawn of husk should be blocked by Mega Torch while spider will spawn in the range of Mega Torch (time set night).

**Testing code**
_spawner.json_
[
  {
    "mob": "minecraft:husk",
    "persecond": 2,
    "attempts": 50,
    "amount": {
      "minimum": 3,
      "maximum": 5,
      "groupdistance": 15
    },
    "conditions": {
      "dimension": "minecraft:overworld",
      "mindist": 10,
      "maxdist": 60,
      "minheight": 20,
      "maxheight": 150,
      "maxthis": 30
    }
  },
{
    "mob": "minecraft:spider",
    "persecond": 2,
    "attempts": 50,
    "amount": {
      "minimum": 3,
      "maximum": 5,
      "groupdistance": 15
    },
    "conditions": {
      "dimension": "minecraft:overworld",
      "mindist": 10,
      "maxdist": 60,
      "minheight": 20,
      "maxheight": 150,
	  "maxthis": 30
    }
  } 
]

_spawn.json_
[
{
    "mob": ["minecraft:spider"],
    "dimension": "minecraft:overworld",
	"seesky":"true",
    "result": "default"
  }
]

**Versions**
Minecraft version: 1.18.2
Forge version: 40.2.1
Mod Torchmaster version: torchmaster-18.1.0
Mod In Control! version: incontrol-1.18-6.1.8

**Comment by Xalcon** [comment]
This is unfortunately a known issue. If torch master blocks a mob from spawning but another mod doesn't check for the current event result and just overrides it, there is nothing I can do - assuming this is the problem still.

I'll look into it
