### ISSUE TITLE
Incompatibility w/ Project Red Illumination

### ISSUE THREAD

**Issue by WenXin20** [Xalcon/TorchMaster#21]
Forge 2281-1.10.2
Project Red v4.8.2.41
Torch Master v1.2.2.25
I found out that after adding the project red lanterns to the config, the lanterns will go inside the Terrain Lighter, but the lighter refuses to place the lantern.

**Comment by Xalcon** [comment]
I've uploaded v1.3.4.39 for MC 1.11.2 and v1.2.3.27 for MC 1.10.2 on curseforge which fix this issue.
They should be available in a bit. Thanks for the report :)

**Comment by WenXin20** [comment]
Thanks for the fix. :)
