### ISSUE TITLE
Compatibility with Pixelmon

### ISSUE THREAD

**Issue by Noko005** [Xalcon/TorchMaster#211]
There are compatibility issues with the Pixelmon mod. I'm sure it's because Pixelmon uses a weird spawning mechanism, but is there any way to make it so the torches/lamps stop Pixelmon spawning? I even put the Torchmaster mod checks to highest priority.

Minecraft version - 1.16.5
Forge version - 36.2.39
Torchmaster version - 2.3.7
Pixelmon version - 9.1.5

![image (3)](https://github.com/Xalcon/TorchMaster/assets/104417043/fc2eb37e-6692-4f4a-a447-034acd5f64cd)
![image (4)](https://github.com/Xalcon/TorchMaster/assets/104417043/2a84ccfa-fd59-452a-a36b-61cc6beff4bf)

**Comment by Xalcon** [comment]
It seems they have their own API with their own spawn events, so it's technically possible. I will need to look into optional dependencies to get this working, not sure if this is still a thing.

**Comment by Noko005** [comment]
Alright, thank you! Please lmk if you find anything :D
