### ISSUE TITLE
Frozen Pearl does nothing - Feral Flare lantern light sources aren't disappearing

### ISSUE THREAD

**Issue by GAndrews98** [Xalcon/TorchMaster#212]
Hopefully this isn't a duplicate as I saw a few similar issues already posted, but they were marked as fixed.

## Setup:
TorchMaster - 19.2.90
All The Mods 8 - 1.0.21b and 1.0.22 (and possibly previous) 
Forge - 43.2.14
Minecraft - 1.19.2

Self hosting a multiplayer server

## Issue:
After breaking the Feral Flare lantern, the light sources remain (forever). There doesn't seem to be any way to remove them.
The Frozen Pearl makes a noise when right clicked but doesn't appear to do anything at all. 
_Some_ of the invisible sources do go away when the lantern is broken, but most remain. 

## Others with similar issues:
- [Reddit: Feral Flare lantern lights not going away](https://www.reddit.com/r/allthemods/comments/14q3af5/feral_flare_lantern_lights_not_going_away/)
- [Imgur: Some Discord users with similar issues](https://imgur.com/a/JkFKfKY)

## Things I've tried:
- Using the Frozen Pearl in every way I can think of. Clicking blocks, shift clicking, running around clicking, etc. Nothing happens aside from a sound effect. The invisible light sources remain.
- Restarting server.
- Filling the entire room with blocks and then breaking them again.
- Placing and breaking the lantern again. 

## Additional notes:
- _Sometimes_ replacing the walls in my mob spawner with a vanilla block (instead of a connected texture block from Rechiseled) seems to help. **But then the light comes back** seemingly randomly (possibly when leaving the chunk, despite it being chunkloaded, or possibly after a server restart). 
- At one point I had 2 lanterns placed because I didn't know the radius. This may be related? 
- The chunks are loaded using FTB Chunks.

## Images:
![2023-07-17_19 32 37](https://github.com/Xalcon/TorchMaster/assets/7970321/6b50c868-0b5d-4737-b24a-b789bce8f876)
Invisible light source in spawner room remains, despite breaking lantern and using pearl.
![2023-07-17_19 33 10](https://github.com/Xalcon/TorchMaster/assets/7970321/c228bc60-93f8-4383-a4e0-713c55580bc1)
Rooms still (somewhat) lit up.
![2023-07-17_19 33 36](https://github.com/Xalcon/TorchMaster/assets/7970321/136bb900-4efb-4620-800d-d96de6ddc384)
Rooms still (somewhat) lit up.
![2023-07-17_19 58 05](https://github.com/Xalcon/TorchMaster/assets/7970321/a924cb89-5f19-46c3-9292-ff96e20217af)
Entire above ground area is lit up still despite no light sources of any kind. (Lantern used to be placed under this area).

**Comment by Xalcon** [comment]
Thank you for reporting this issue. I've been looking into this and atleast in a local dev environment, I'm unable to replicate it.
The pearl removes all light sources placed by the lantern and removing the lantern removes all light sources as well.

I've also installed ATM8 1.0.22 and atleast in singleplayer, the lantern behaves as expected. This sounds like a mod compatibility issue. Are you able to replicate this issue in a new world or far away from your base? It might be some other mod messing with my light sources. I'll continue investigating this, but this isn't a trivial issue it seems.

**Comment by GAndrews98** [comment]
Thanks for looking into it! 

I'll try my best to replicate it and let you know what I figure out.

**Comment by Xalcon** [comment]
Something to consider, these may very well not be feral flare lantern light sources but lights from a different mod. I was able to find some lit spots in a forrest but have yet to figure out how to determine what block it is without writing a mod to dump the info.

Interestingly, these light sources are light level 13 and can be found mid air - the feral flare lantern never places light sources mid air.

I need to figure out what block this is (F3 doesnt help here unfortunately since they are "air" blocks)

**Comment by GAndrews98** [comment]
That's interesting. I haven't noticed any other weird light sources like this in my world, but that doesn't mean they don't exist. 

Is there some way to see a light source from the Feral Flare lantern? Also, are all invisible light sources the same light level?

I've spent about 2 hours trying to replicate the issue in the same server a few hundred blocks away and everything is behaving as it should. I tried creating a similar environment to what I had (2 lanterns relatively close, underground, with a dark room on the surface), and it all seems to be working fine. Breaking the lantern(s) immediately clears the light sources, I don't even need the pearl. I did notice that placing a block on one of the invisible light sources gets rid of it, which doesn't happen at my main base where the bug is. 

I also loaded up the world in single player and tried using the Pearl but it made no difference. 

All I can figure is that there is either another mod causing the light sources (which I doubt because it's in the exact same radius as where I had the lantern placed) or maybe the server crashed or restarted at some point causing some weird chunk saving problem? I've tried replicating it with both loaded and unloaded chunks and everything is working fine. The only thing I can't easily replicate is the timing or a possible server crash.

If you'd like me to provide the world download somehow I can. But I'm not sure it would help since we can't reproduce the problem.

**Comment by GAndrews98** [comment]
Yeah there's something really weird going on in my world. I'm beginning to think it may not be related to the Feral Flare lantern after all.

Breaking torches nearby (more than 16 but less than 64 blocks from where the lantern was) _sometimes_ leaves a lingering light source. But not always.

**Comment by Xalcon** [comment]
I'm interested in resolving this issue, even if torch master is not at fault. I'll look into adding an item or a command to identify the source of these lights

**Comment by GAndrews98** [comment]
Yeah that'd be awesome! 

[I made a clip of what's going on in my world.](https://medal.tv/games/minecraft/clips/1kfvdsPaW_f5sX/yXZCzjBbqHyY) It's very bizarre and probably isn't an issue with your mod after all. 

The bug seen in this video only happens with torches (or any light source) that have existed for a long time and not newly placed torches. The glow that is seen lingering is exactly what happens in the rest of my base and I only noticed it after using the Feral Flare lantern which I why I first assumed it to be the cause.

**Comment by BartHageman** [comment]
I'm experiencing the exact same issue, had strange lights appear inside my mob farm. (It's usually pitch black). I was able to clear one out using the frozen pearl, but there was still something generating light that I can't seem to get rid of. Have since broken both my lanterns, and relocated my mob farm, filled it in with cobblestone to clear it out, but no luck :/

I'm also on ATM8 1.0.22, TorchMaster 19.2.90. Single player world.

**Comment by BartHageman** [comment]
Update: I disabled the starlight mod, filled the spawner in with blocks and broke them again and that seems to have cleared out the invisible lights somehow.

**Comment by Xalcon** [comment]
Interesting, so its actually an optimization mod causing this? Makes sense I guess. I'll leave this issue open for now, just in case. 
Thanks for your help on this @BartHageman - lets hope there is nothing else.
