### ISSUE TITLE
Mega Torch Blocks Enderio Spawners

### ISSUE THREAD

**Issue by tyler489** [Xalcon/TorchMaster#213]
Would it be possible to exempt Enderio Spawners from being blocked by mega torches in 1.20?

**Comment by Xalcon** [comment]
Nice to see enderio showing some activity. 

I can confirm that this is probably a bug on my side. I expect that all Spawners are a `SpawnerBlockEntity` which only applies to vanilla spawners. I'll change that, thanks for the report.

**Comment by Xalcon** [comment]
This bug was fixed in 
- v20.1.1 for MC 1.20.1
- v19.4.1 for MC 1.19.4

Other versions did not have said logic and shouldn't be affected
