### ISSUE TITLE
Mega Torch Causes Game Crash When Converting Zombie Villager

### ISSUE THREAD

**Issue by Pa-nts** [Xalcon/TorchMaster#215]
If you try to convert a Villager into a zombie villager while in the area of a mega torch, it causes the game to crash.
[crash-2023-07-27_09.50.38-server.txt](https://github.com/Xalcon/TorchMaster/files/12184224/crash-2023-07-27_09.50.38-server.txt)

**Comment by Xalcon** [comment]
Interesting - I did change something that could have an effect on this. I see you are using 20.1.1, could you try version 20.1.2? I've released that version a few hours before you reported this bug, so I guess you just missed the update.

**Comment by Xalcon** [comment]
i did test it myself with version 20.1.2 and its working fine, so updating should do the trick

**Comment by Pa-nts** [comment]
Sick, Ty.
