### ISSUE TITLE
Issue tabs

### ISSUE THREAD

**Issue by castilio20** [Xalcon/TorchMaster#219]
it seems the mods mess with the tabs a little
![Screenshot_18](https://github.com/Xalcon/TorchMaster/assets/76228548/fec418d1-bba7-4130-9cec-70849eaa5135)
(it should not be in the vanilla tabs)
![Screenshot_17](https://github.com/Xalcon/TorchMaster/assets/76228548/9cf8ce37-ef73-4ae2-8728-d5eda8298fbe)
not 100%sure if this one is bc your tab is moved it may be

**Comment by Xalcon** [comment]
It doesn't happen for me in dev - not sure whats going on here, but I have an idea what could be the issue.

**Comment by Xalcon** [comment]
This should be fixed with the previous commit - closing.
