### ISSUE TITLE
Mobs spawns near the torch?

### ISSUE THREAD

**Issue by Hund** [Xalcon/TorchMaster#22]
I have the range set to 128: `I:MegaTorchRange=128` on my SMP, but they spawn very close none the less. :/

![2017-05-27_16 58 12](https://cloud.githubusercontent.com/assets/320498/26522324/5b371e52-42fe-11e7-977b-770f6b53df19.png)

* Minecraft 1.11.2
* Forge 13.20.0.2304
* TorchMaster 1.3.3.37

I just checked and the client has the option set to `32`, does that matter?

**Comment by Xalcon** [comment]
This should only happen if the torch is not chunk loaded.

**Comment by Hund** [comment]
I'm always close to my home where the torch is.

**Comment by Xalcon** [comment]
I'm not sure what the issue could be. Some mods might cause additional spawns that dont use CheckSpawn, but i dare to say this is not the issue in your case.

Please try chunkloading the torch chunk if possible.

Also: Mobs are not allowed to spawn inside the radius, but they can still walk inside. This might also be an issue.

**Comment by Hund** [comment]
I use very few mods, where Botania is the only 'game changing' one. And I don't have any chunk loaders.

And that I'm aware of, but they usually don't walk around that much. The range is 128, so I find it unlikley they'll walked that far in a few minutes. :/

**Comment by Hund** [comment]
Is there any downsides to a larger range? Like performance? I could try to max it out.

**Comment by Xalcon** [comment]
no range does not affect performance at all, just make sure the torch is always loaded. I think the default range is 10 chunks (160 blocks). Setting the radius higher wouldnt have an effect since a player cant load more chunks by default. You could also try placing more torches (a bit spread out) to increase the chance that a torch is loaded.

**Comment by Xalcon** [comment]
@Hund any news on this?

**Comment by Hund** [comment]
Uhm. I added a chunkloader to my world as a temporary solution.

When I go to the Nether and come back, it's like there's a delay on the torch (that's close to the portal) when the chunks gets loaded again and mobs has a chance of spawning? Keeping the area chunkloaded helps though.

**Comment by Xalcon** [comment]
this might be the issue. The delay is related to chunkloading sadly.
When a player moves to a new dimension, the chunk system loads the closest chunks first. If those chunks do not contain a torch, mobs will be allowed to spawn until the torch is loaded. 

If you move the torch to the portal, mobs shouldnt be able to spawn when moving between the nether and the overworld. Sadly, there is still a chance of spawning when logging into the world while not being close to the portal.

There is a way to fix this, but it requires a fair amount of refactoring. I'm still not sure how to persist the torch information across world reloads/server restarts, among some other issues like the new burnout feature. But this I will handle in #23

**Comment by Xalcon** [comment]
Feature implemented in the v1.12 version of the mod. Earlier versions of MC will still require a chunkloader.
