### ISSUE TITLE
Mega torch blocks vanilla spawner

### ISSUE THREAD

**Issue by Nerxxy** [Xalcon/TorchMaster#220]
Playing stoneblock 3 pack, config is set to only block natural mobs yet also blocks vanilla spawner 😢

**Comment by Xalcon** [comment]
Stoneblock 3 is running on MC 1.18 with Torchmaster 18.1.0 - current version is 18.2.1
I've tested 18.2.1 in my local dev instance and the spawner is working fine with `blockOnlyNaturalSpawns = true` (the default) - i didn't do any changes to the spawning logic in the meantime, but it might be related to the modpack itself.

**Comment by Xalcon** [comment]
Just tested in StoneBlock 3 v1.7.1 with Torchmaster 18.1 - its working perfectly fine. Screenshot was done with Nightvision and Torch encased in dark glas to prevent the area from being lit (Vanilla Spawners require a low light level to work)
![image](https://github.com/Xalcon/TorchMaster/assets/5042450/e24a22a6-546a-42e2-a4ce-e283c79cfc74)

**Comment by Nerxxy** [comment]
Hmm ok what i was doing didnt encase the torch in dark glass ill try encasing it next time, but wouldnt that defeat the purpose of lighting an area while letting spawners work? Since the dark glass prevents light? Or am i thinking of something different? Will send a screenshot of my setup once im back on.

**Comment by Xalcon** [comment]
Well, thats just how vanilla spawners work. If it is too bright, the spawners stop working - thats why you can disable them by placing torches around them.

**Comment by Nerxxy** [comment]
Yeah ik that, i was just under the assumption that it would let spawners work no matter the light level as long as the area was only lit by the mega torch, i guess i just misunderstood the description

**Comment by Xalcon** [comment]
Yes, this is unfortunately not something that I can easily change. I'll close this then.

**Comment by Nerxxy** [comment]
As a side note in a 9x9x5 room with the spawner in the middle on one side i have tinted glass from mob grinding utils, how would i go about lighting it up? Since the tinted glass makes it quite literally impossible to see through, or would i need go use a different glass?

**Comment by Xalcon** [comment]
I don't know when the light level change was introduced but if it is in 1.18 or earlier, mobs can only spawn in locations with light level 0 - in this case, you don't want any light in your spawning chamber.

**Comment by Nerxxy** [comment]
damn ok, i was hoping it would let me see into the room with the spawner i guess thats not possible 😢

there was a mod in stone block 2 (cant remember the name of it) but it had a block called the lapis lamp, its basically just the redstone lamp from vanilla but it lets mobs spawn while providing light in the mob farm chamber/are whatever u wanna call it, i was hoping the mega torch worked the same :/ anyways thanks for the help keep up the good work 😃

**Comment by Nerxxy** [comment]
what i read i was under the impression i was able to do this the glass used is tinted glass by mob grinding utils
![image](https://github.com/Xalcon/TorchMaster/assets/37718547/1cb89569-06b1-46ff-b6cc-ad3c8053e7c7)

**Comment by Xalcon** [comment]
Yeah, that unfortunately is not possible - the room needs to be completly dark. You can put the torch somewhere else where it doesnt illuminate the room.
