### ISSUE TITLE
[Suggestions] Megatorches block Grave Guardians. They shouldn't.

### ISSUE THREAD

**Issue by cthae** [Xalcon/TorchMaster#224]
Grave Guardians (from Corail Tombstone) are peaceful mobs and as such, they shouldn't be blocked. Moreover, you can trade with them. That's another important reason not to block them. If you could add an exception, or a more general rule for these kinds of entities that would be great.

**Comment by Xalcon** [comment]
I'm using the following logic to determine if an entity should be added to the MegaTorch block list:
https://github.com/Xalcon/TorchMaster/blob/2987c8231c6688148b3372caef9f507d96e2e43f/src/main/java/net/xalcon/torchmaster/compat/VanillaCompat.java#L14
Unfortunately, this only checks if the entity is friendly - but there is no "neutral" check available - but this works in 99% of use cases.

Question: Is the Grave Guardian Friendly or Neutral? I.e. will it attack a player if the player attacks the guardian?
I can add specialized compatibility to torchmaster for this mob, but its also possible to handle this via the torchmaster config:
```
megaTorchEntityBlockListOverrides = [ "-modname:monstername" ]
```
Replace the `modname:monstername` with the internal name of the monster that you want to remove from the block list. Make sure you keep the `-` in front of the modname. I'll look into adding this as a compatibility patch into Torchmaster.

**Comment by Xalcon** [comment]
I've just checked and it seems this is working as intended. The Mega Torch does infact NOT block the grave guardian. The Blocklist (which is printed to the admin console when using the `/torchmaster entitydump` command) for the mega torch does not contain the Grave Guardian.
The grave guardian is correctly added to the Dread Lamp List. Do you have a Dreadlamp nearby?
There is no way for me to know which friendly entities are wanted and which are not. Some people want wandering traders (and similar entities), others hate them. For these cases I've added above configuration option. You can remove the grave guardian from the DreadLamp list like this:
```
dreadLampEntityBlockListOverrides = ["-tombstone:grave_guardian"]
```
This was tested with Corail Tombstone v8.5.5 and Torchmaster 20.1.4

**Comment by Corail31** [comment]
@Xalcon I only noticed this issue now, but it can confirm you that my peaceful creatures are in category creature or misc ;)
