### ISSUE TITLE
(ATM9) Feral Flare Lantern either has no GUI, or GUI is unable to be opened.

### ISSUE THREAD

**Issue by mcjonesmike** [Xalcon/TorchMaster#228]
Just trying to get the feral flare lantern to only place lights in line of sight, but I'm unable to open the GUI by right clicking. Version 20.1.5.

Steps to reproduce

1) place feral flare lantern in world
2) right click
3) GUI doesn't open

Thank you!

**Comment by Xalcon** [comment]
This is not a bug. The feature is simply not implemented at this moment
