### ISSUE TITLE
[Bug]: 1.21.1 Neoforge Invisible light bug

### ISSUE THREAD

**Issue by aAndrew3030** [Xalcon/TorchMaster#234]
### Torchmaster Version

21.0.0

### Mod Loader

Neoforge

### What happened?

The invisible lights placed by torchmaster prevent being able to place a block in the block space the light is placed. Removing the lantern removes the light and reverts everything back to normal.

**Comment by aAndrew3030** [comment]
Also, if the frozen pearl is implemented in this version, it does not show in EMI?

**Comment by Xalcon** [comment]
Frozen Pearl is indeed not implemented as I didn't see the need for it. It was previously intended to be an admin tool. If it is needed again, I will add it back.

I was able to reproduce the issue, I forgot to mark them as replaceable. Will be fixed in 21.0.1 for both Fabric and Neoforge

**Comment by Xalcon** [comment]
Update is available on modrinth and curseforge.
