### ISSUE TITLE
[Bug]: [1.21] Torchmaster for 1.21 is requesting a newer version of MC

### ISSUE THREAD

**Issue by Periam** [Xalcon/TorchMaster#235]
### Torchmaster Version

torchmaster-neoforge-1.21-0.12.13

### Mod Loader

Neoforge

### Mod Loader Version

neoforge-21.0.167

### What happened?

After installing the latest version of the mod it started to request a MC for 1.21.1

![Screenshot 2024-09-02 125544](https://github.com/user-attachments/assets/7e3b6467-b582-491d-85a1-a333ece1dcaa)
![Screenshot 2024-09-02 125645](https://github.com/user-attachments/assets/0cfa4417-e936-4c3a-9a83-607bcc46f815)

**Comment by Xalcon** [comment]
Well, thats annoying. I can update the files on curseforge and modrinth to not include 1.21 and only allow 1.21.1+ installations. Would that be sufficient or do we need actual builds for 1.21?

**Comment by Xalcon** [comment]
I've updated the files to not allow installations on unsupported MC Versions. I do not intend to support 1.21 for too long, considering that 1.21.1 is out and 1.21.2 is coming soon.

**Comment by Periam** [comment]
Thanks
