### ISSUE TITLE
[Bug]: 1.21 Torchmaster causing crash

### ISSUE THREAD

**Issue by Gamemassa** [Xalcon/TorchMaster#237]
### Torchmaster Version

21.0.0 and 21.0.1

### Mod Loader

Fabric

### Mod Loader Version

0.16.3

### What happened?

Torchmaster 21.0.0 was working on Minecraft 1.21 until a few days ago when I updated Fabric to 0.16.3 and Fabric API to 0.102.0, and Torchmaster suddenly started causing a crash when I tried to load into my SP world (crash report below), so I updated Torchmaster to 21.0.1, and that one says it's not compatible with Minecraft 1.21, so I'm a bit confused.

### Relevant log output

Crash Report:
https://mclo.gs/49dDXOW

Latest.log
https://mclo.gs/Gv2HHWs

**Comment by Xalcon** [comment]
Would it be possible for your to update to 1.21.1? Torchmaster 21.0.1 is compiled against 1.21.1 and it seems fabric doesnt like that.

**Comment by Xalcon** [comment]
I've been looking through the logs and trying different versions, but I can't replicate the crash.

When I create a new pack with the following versions, I can play single player just fine. The world loads without crashing and I can place all of my blocks.
* Fabric Loader 0.16.3
* Fabric API 0.102.0+1.21
* Torchmaster 21.0.0

Does this crash happen for you in a new world as well?
It might be related to a different mod, even though I'd be a bit suprised for this specific case.
Are you playing a custom modpack? I'd like to see if I can replicate it myself.

**Comment by Gamemassa** [comment]
> I've been looking through the logs and trying different versions, but I can't replicate the crash.
> 
> When I create a new pack with the following versions, I can play single player just fine. The world loads without crashing and I can place all of my blocks.
> 
> * Fabric Loader 0.16.3
> * Fabric API 0.102.0+1.21
> * Torchmaster 21.0.0
> 
> Does this crash happen for you in a new world as well? It might be related to a different mod, even though I'd be a bit suprised for this specific case. Are you playing a custom modpack? I'd like to see if I can replicate it myself.

Yes, I'm using a custom modpack. I actually haven't tried to make another new SP world since I updated Fabric, so I might try that in a bit.

**Comment by Xalcon** [comment]
I expect it to crash in a new world - but if it doesn't, then its definitely a weird mod interaction.
Either way, I'd like to test with your modpack, maybe I can drill down a bit deeper and figure out whats going on. The Errorlogs unfortunately only tell me that one of my mixins is at fault but no details about whats actually going on.

**Comment by Gamemassa** [comment]
> I expect it to crash in a new world - but if it doesn't, then its definitely a weird mod interaction. Either way, I'd like to test with your modpack, maybe I can drill down a bit deeper and figure out whats going on. The Errorlogs unfortunately only tell me that one of my mixins is at fault but no details about whats actually going on.

I just tried making a new world, and I'm not sure if your mod is causing this, but when I click Create it starts to prepare and then hangs at 0% forever.

Also, as far as my modpack, you'll have to give me a few minutes to shove it into a zip file and throw it into Dropbox or something, because I use the vanilla Minecraft launcher, not Modrinth or Curseforge launchers.

**Comment by Xalcon** [comment]
No worries, take your time. I'm sorry this is causing issues for you and I'm not sure if I will be able to find the issue today (it's getting late for me), but I'll definitely prioritize this tomorrow.

**Comment by Gamemassa** [comment]
> No worries, take your time. I'm sorry this is causing issues for you and I'm not sure if I will be able to find the issue today (it's getting late for me), but I'll definitely prioritize this tomorrow.

Ok, here's my custom modpack (in its current state anyway; might add more in the future)
https://www.dropbox.com/scl/fi/4e65t155co3kmijxxx5ow/Gamemassa-s-MC-1.21-Modpack-v1.zip?rlkey=4dwjc4odzulyjc7eilqrqn20c&st=6dsfzbxu&dl=0

Also, after removing Torchmaster I was able to create a new SP world without my game hanging infinitely, so Torchmaster was definitely causing that.

**Comment by Xalcon** [comment]
Thank you, this helped a lot. I was able to find the issue, but it's not trivial to fix. This is an incompatibility with Architectury, a libary mod for a bunch of other mods. I'll look into possible solutions.

**Comment by Xalcon** [comment]
I've implemented a workaround that will cause some edgecases to not be blocked properly. Specifically mob spawns on chunk generation will currently not be blocked due to the incompatibility with architectury. I'll need to implement a few things, including switching from redirects to injects - but this edge case only comes up when using torches with very high radius configurations and while exploring. The normal blocking should work.

I'll release an update in a bit, specifically the following versions should now work with architectury:
Torchmaster 21.0.2 for MC 1.21 (Fabric)
Torchmaster 21.1.0 for MC 1.21.1 (Fabric)

**Comment by Gamemassa** [comment]
> I've implemented a workaround that will cause some edgecases to not be blocked properly. Specifically mob spawns on chunk generation will currently not be blocked due to the incompatibility with architectury. I'll need to implement a few things, including switching from redirects to injects - but this edge case only comes up when using torches with very high radius configurations and while exploring. The normal blocking should work.
> 
> I'll release an update in a bit, specifically the following versions should now work with architectury: Torchmaster 21.0.2 for MC 1.21 (Fabric) Torchmaster 21.1.0 for MC 1.21.1 (Fabric)

Oh damn, that was fast. Also I've just tested and I can confirm that 21.0.2 is working with my modpack. Thanks for much for the quick responses!

**Comment by Xalcon** [comment]
Okay, thanks for letting me know.
