### ISSUE TITLE
No server support?

### ISSUE THREAD

**Issue by chaoskie** [Xalcon/TorchMaster#24]
Tried you mod on my server modpack. It doesn't add the items nor the config. After copying the config from a SSP game the recipes became available but the items are uncraftable and do not apear in the creative overview (NEI can see them, thats how I know they should be available). We managed to cheat it in through NEI but it dissapears straight away.
Do you know perhaps what could cause this and how we should fix it?
The world is brand new, seems like the mod is just not accepted by the server for some reason
(no errors so I can't give you an error message; this is the mod list:

AbyssalCraft-1.11.2-1.9.4-pre-3.jar              
Levels 2-1.11.2-r1.2.8.jar
advancedcombat-1.0.1-[1.11.2].jar              
  lightningcraft-2.8.4-[1.11.2].jar
Aroma1997Core-1.11.2-1.2.0.0.jar              
   malisiscore-1.11.2-5.1.1.jar
Aroma1997s-Dimensional-World-1.11.2-1.3.0.0.jar  
malisisdoors-1.11.2-6.1.0.jar
astralsorcery-1.4.1.jar                          
Mantle-1.11.2-1.2.0.26.jar
Baubles-1.11-1.4.5.jar                          
 minecolonies-universal-1.11.2-0.8.1784.jar
BiblioCraft[v2.3.1][MC1.11.2].jar             
   MmmMmmMmmMmm-1.11.2-1.13.jar
bigbattery-1.11.2-0.1.4.jar                     
 MoreFurnaces-1.11.2-1.9.5.jar
BiomesOPlenty-1.11.2-6.1.0.2238-universal.jar    
Morpheus-1.11.2-3.2.14.jar
BloodMagic-1.11-2.1.10-79.jar                    
NotEnoughItems-1.11.2-2.2.0.216-universal.jar
Bloodmoon-MC1.11-1.5.1.jar                       
NuclearCraft-2.2d--1.11.2.jar
Bookshelf-1.11.2-1.5.0.371.jar                  
 QuickLeafDecay-MC1.11.2-1.2.3.jar
Botania r1.9-343.jar                            
 reptilemod-1.11.2-3.6.2-67.jar
Chameleon-1.11.2-3.1.0.jar                     
  roots-2-0.017.jar
Chisel-MC1.11.2-0.0.10.14.jar                   
 RuneCraft 1.11.2 by XxRexRaptorxX (v.1.4.0).jar
CodeChickenLib-1.11.2-2.6.0.254-universal.jar   
 serversync-2.6.9.jar
CraftableElytra-1.1-1.11.2.jar                  
 SimpleDimensions-MC1.11-1.3.jar
Currency-1.11.2-1.0.3.jar                        
SpartanShields-1.11.2-1.3a.jar
cxlibrary-1.11.2-1.4.0.jar                       
TConstruct-1.11.2-2.7.0.26.jar
CyclopsCore-1.11.2-0.10.3.jar                   
 toolprogression-1.11.2-1.0.5.jar
embers-0.212.jar                                
 torchmaster_1.11.2-1.3.4.39.jar
EpicSiegeMod-12.0.157.jar                       
 toroquest-1.11.2-3.5.jar
EvilCraft-1.11.2-0.10.25.jar                   
  Totemic-1.11.2-0.8.6.jar
extrautils2-1.11.2-1.4.1.jar                     
TreeChopper-1.11.2-1.1.2.jar
fairylights-2.1.0-1.11.2.jar                     
UniDict-1.11.2-1.0.jar
GraveStone Mod 1.7.2.jar                        
 WanionLib-1.11.2-1.0.jar
Guide-API-1.11.2-2.1.1-52.jar                  
  Wawla-1.11.2-2.4.0.231.jar
Hwyla-1.8.13-B26_1.11.jar                       
 Waystones_1.11.2-3.0.16.jar               
WearableBackpacks-1.11.2-2.3.2.jar
industrialcraft-2-2.7.33-ex111.jar            
   worldedit-forge-mc1.11-6.1.6-dist.jar
ironchest-1.11.2-7.0.19.803.jar                  
worldlimiter-1.11.2-1.1.0.jar

**Comment by Xalcon** [comment]
Torchmaster should work just fine on the server. The behavior you describe sound like the mod is not available on the server side. The server logfile might have more information. Could you upload the latest server logfile to https://pastebin.com or https://gist.github.com and link it here?

**Comment by Xalcon** [comment]
I've just setup a clean installation of forge 13.20.0.2304 (Server + Client) and installed the latest Torchmaster  Release (1.3.4.39) and I was unable to replicate the issue. JEI shows the recipe just fine and crafting works as expected. I dont think this issue is on my end. Please make sure you've installed the correct version of Torchmaster for 1.11.2 on your server. If the issue still persist, try to replicate it with the least amount of mods possible.

**Comment by chaoskie** [comment]
I just ventured through the logs this is what I found
https://pastebin.com/0vTW1bze

I'll try later today with the newest forge install as I currently am not able to do so

**Comment by Xalcon** [comment]
Looks like the jar is corrupt. Re-download the mod for the server.

Here are the file hashes so you can make sure you got the right file. You can calculate the hashes for your torchmaster jar via https://md5file.com/calculator

| torchmaster_1.11.2-1.3.4.39.jar | (n/a) - 83159 bytes |
| ----- | ----- |
| MD5 | 0baeb36799b30c47599bf902ef752a60 |
| SHA-1 | f659c06f18138e899dbbfda647fc1784d07d5bdd |
| SHA-256 | 8aa6c6af55e1dc2cd0cf1bcec4290b72bf51f9555e6406275ccdd20fea0d021b |
| SHA-384 | 7382afb15acf52c4dc51a31cf8ccec84c702348eb6a47926dac5652a05513cb955446ab9c785113bc39236d77c16cf72 |
| SHA-512 | ff4df65cea32728f2a98163eb9d951a21cc29f7156c80bac9dcb7b497b16002dfd30bb83037740f10cac4654088acbce14fbdcbbac2d40a410c7227ae409985a |

**Comment by Xalcon** [comment]
Any news on this? @chaoskie

**Comment by chaoskie** [comment]
my bad, I really need to learn to check GIT more regularly
but yes it works now, I traced it down to my firewall that decided a single part of the file had to be blocked, so a bunch of data never made it yet it had enough to not let it crash entirely. 
Besides that, I'd like to get started with a few mod ideas too, can I contact you incase I have questions about a few things? (no worries I'm no full retard, but it's easier knowing you can ask someone who knows a bit more about modding when you get stuck somewhere.)

**Comment by Xalcon** [comment]
i suggest hopping onto discord, i hang around in the Minecraft Mod Development (MMD) Discord pretty much all the time. https://discordapp.com/invite/2QpDWmh (or see https://www.reddit.com/r/feedthebeast/ in the sidebar on the right is a list of Discord servers, including MMD)
