### ISSUE TITLE
Feature: Add Debug Renderer that visualizes the work volume of the lamp/torch

### ISSUE THREAD

**Issue by Xalcon** [Xalcon/TorchMaster#25]
Title. 
* Requires config sync from server to client to be able to render the correct size all the time
* Render toggle via shift-righclick with an empty hand
* Render an always visible cube on the torch when the volume is visible to aid finding the torch that causes the rendering
* Allow coloring of the renderer by applying any minecraft dye to it (will not use the dye)
* Rendering needs to be done as efficient as possible to allow having it on for longer durations
* Config options for:
  * Render all torches vs only self-enabled?
  * **Stop rendering** on logoff vs **stay on** on relog?

**Comment by Knito58** [comment]
Nice ideas. I tend to hide the mega torch in the base in a wall or under the floor and then to forget about the placement. Some device would be nice which switches the debug radiuss of 
a) ALL mega torches or 
b) the nearest torch
on and off as well as a visual hint where the torch is placed.

**Comment by Felthry** [comment]
Any chance of a timeline on this? It'd be really useful. I've just started using RFTools builders in support mode as a workaround for now, but a built-in feature would be greatly helpful.

**Comment by angelnc1989** [comment]
I came to the issue tracker to request such a feature.
My suggestion would have been to turn it on with a Redstone Torch placed next to it, like the BuildCraft Land Mark.

**Comment by Xalcon** [comment]
I've actually started working on it a while ago but I have some other technical issues that need to be solved first, i.e. how this debug renderer should look like and writing it in a way that doesnt slow down mc to a crawl when you have a dozen of those active. Currently, I'm still busy with work, so I dont have much time to work on this at all until my vacation mid august. 

This will definitely be a feature in the next release though!

**Comment by Knito58** [comment]
:)))

**Comment by Xalcon** [comment]
this feature has been implemented but still has some technical issues. I wont be able to fix those issues for the next release. They are nothing major (just some z fighting when 2 torches are visualized at the same time while sharing one ore more axis - which should happen rarely during normal play/outside of testing)

I want to get this feature out so I can gather some feedback. The z fighting might get fixed sometime early next year.
