### ISSUE TITLE
Missing Recipes

### ISSUE THREAD

**Issue by InsomniaKitten** [Xalcon/TorchMaster#26]
Mod items cannot be crafted, and also have no recipes in JEI,

**Mod version:** [1.4.0.3](https://minecraft.curseforge.com/projects/torchmaster/files/2434694)
**Forge version:** [1.12-14.21.0.2331](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.0.2331/forge-1.12-14.21.0.2331-changelog.txt)

![screenshot](http://i.imgur.com/pF9lbSh.png)

**Comment by Xalcon** [comment]
D: what did they change this time?! 
I'll take a look.
