### ISSUE TITLE
[feature request] helpful info tooltips

### ISSUE THREAD

**Issue by Zygus42** [Xalcon/TorchMaster#28]
A tooltip on each item quickly describing what it does, so that if I'm looking at a "Dread Lamp" for example, I know what it does.  People on my server will never make one otherwise.

**Comment by Xalcon** [comment]
sounds like a reasonable request.

**Comment by Xalcon** [comment]
feature implemented in the MC 1.12 version of the mod. I might backport it to earlier versions, will see.
Update will be up on curseforge in a few hours (still alpha, testing a new feature)
