### ISSUE TITLE
The mega torch disables the vanilla mob spawner block

### ISSUE THREAD

**Issue by Hund** [Xalcon/TorchMaster#3]
The Mega Torch disabled the vanilla mob spawner block on my survival multiplayer server. And I also created a new singleplayer world and it's the same thing there.

* Forge 12.18.2.2183
* TorchMaster 1.1.0.8

I'm not sure what else to include in this ticket, but let me know if you need anything. :)

**Comment by Xalcon** [comment]
I know I said you should open a ticket but I opened one already in the meantime :P see #2 
/closed

**Comment by Hund** [comment]
Oh. Err.. I haven't had any coffee at the time. :P
