### ISSUE TITLE
[1.12] Console Messages

### ISSUE THREAD

**Issue by NillerMedDild** [Xalcon/TorchMaster#30]
Versions:
Minecraft 1.12
Forge 14.21.1.2395
TorchMaster 1.12-1.5.0.31

Hey! I've been getting a lot of console messages from TorchMaster, and I was wondering if you'd be able to make a config option, to not display them?

![billede](https://user-images.githubusercontent.com/21295394/27976070-3ced6ffa-6365-11e7-872b-5af8126a8e37.png)

**Comment by Xalcon** [comment]
I released an update like an hour ago :P sorry for the spam, i needed some of the info for my tests and forgot that i use a different logging config. Torchmaster now only logs to the console if log4j is configured to print debug messages

**Comment by NillerMedDild** [comment]
Thank you :D
