### ISSUE TITLE
[1.10] Mega Torch not playing nice with Draconic Evolution Stabilized Spawners

### ISSUE THREAD

**Issue by beanzen** [Xalcon/TorchMaster#33]
My setup is as follows:
Minecraft 1.10.2 
Forge 12.18.3.2297
TorchMaster 1.4.0.32
Draconic Evolution 1.10.2-2.1.1.236

Basically the issue is with the "stabilized spawner" from draconic evolution with _hostile_ mobs only. Blazes, specifically, have been giving me an issue. When using the "draconic" (high / orange) tier spawner from draconic evolution with a hostile mob inside, the spawner will not function if within range of a mega torch. The spawner WILL work if the mob is passive, like a sheep. 

I don't know if the conflict is on the part of draconic evolution or the mega torch, but the two don't seem to play together nicely for some reason.

**Comment by Xalcon** [comment]
Meh.. no, without looking into the draconic evolution code, i think i already know the issue. Minecraft Forge 1.12 got a feature that is not present in earlier versions (CheckSpawnEven#isSpawner()). I will see if I can work something out

**Comment by Xalcon** [comment]
Sweet, brandon added the fix on his end, which makes it available for other mods, not just torchmaster :)
Once the next release for DE is out, the torch should just work. I'll keep this issue open until i can verified it myself.
