### ISSUE TITLE
1.12 vanilla spawners not working near Mega Torch

### ISSUE THREAD

**Issue by krelios** [Xalcon/TorchMaster#34]
I have a few mega torches around my base and after bringing a vanilla blaze spawner back from the nether and placing into a mob trap in my base, nothing will spawn.

Resturbed Spawners from EU2 are also blocked.

**Comment by Xalcon** [comment]
please keep in mind that the 1.5 update for torchmaster had some major changes to the torch logic. If anyone updates from 1.4 to 1.5, they will need to break+replace all torches/lamps.
