### ISSUE TITLE
[1.12.1-1.5.2.40] Doesn't work with Forge 2443 (1.12)

### ISSUE THREAD

**Issue by Kris1432** [Xalcon/TorchMaster#35]
Forge: 2443
Version: 1.5.2.40
MC Version: 1.12

Cause: Log says needs 1.12.1

**Comment by Xalcon** [comment]
unlucky, my buildscript writes the current mc version into the mcmod.info :/ guess ill have to change that.
In the meantime you can use 1.5.1 for 1.12. There are no code changes and its just as stable as 1.5.2

**Comment by Xalcon** [comment]
Fixed and released
