### ISSUE TITLE
Add feature to prevent passive mob spawn

### ISSUE THREAD

**Issue by joye-ramone** [Xalcon/TorchMaster#4]
It would be really nice to have an option to prevent spawn of passive mobs too.
Especially useful for squids and bats.
Either via UI on existing item or probably a separate one.

**Comment by Xalcon** [comment]
Feature implemented. Will be available in the 1.2 release (or as a bleeding edge release from my jenkins server)

**Comment by joye-ramone** [comment]
Nice and Thank you!
