### ISSUE TITLE
Question about torch radius

### ISSUE THREAD

**Issue by lmcgrath** [Xalcon/TorchMaster#40]
I can't seem to find whether the Mega Torch radius includes Y axis in addition to X and Z. Does 64 blocks radius mean 64 blocks in all three directions or is the Y axis shorter than the other two like the Extra Utilities Magnum Torch?

**Comment by Xalcon** [comment]
The volume is a cylinder with r = radius (64 by default) and h = r * 2
As far as I know, this is the exact same logic as the magnum torch.

**Comment by sitedyno** [comment]
In case anyone comes here for the same reason I did...

To have full coverage you'll need to place your torches not more than 90 blocks apart on the x and z, or 127 blocks on the diagonal.

Thanks for the mod Xalcon. Apologies for the necro.

**Comment by GrantGryczan** [comment]
This is no longer accurate. It now appears to be a cuboid with length, width, and height all 2 times the radius.
