### ISSUE TITLE
java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by Gamerbolts** [Xalcon/TorchMaster#48]
https://pastebin.com/5qHmhKzE

Hi there I have your mod in my modpack. and something strange happens when the server restarts, it crashes once gives this log, then restarts and is fine. The mod seems to work fine so I'm not sure why its doing that.

I am using
Minecraft v1.12
Forge v2555
TorchMaster v1.6.1.53

Thank you, any help is appreciated :)

**Comment by iamtpage** [comment]
I am also experiencing this issue.

**Comment by Xalcon** [comment]
I dont think this is an issue with torchmaster. The worldevent is fired indicating a new world being loaded but the world object is null. This should not happen and I assume some other mod is messing with forge there. I'll add a delayed retry to prevent those crashes, but this might cause other issues. A better way would be to find out why this happens in the first place.
