### ISSUE TITLE
Mega Torch does not prevent Vampires spawning from Vampirism mod

### ISSUE THREAD

**Issue by iamtpage** [Xalcon/TorchMaster#49]
Hi,

I've discovered that Vampires from the Vampirism mod still spawn in the radius when the torch is set. I've verified this with the latest TorchMaster/Vampirism/Forge/Minecraft versions and I believe it has something to do with how the Vampirism mod defines it's entities.

Vampirism mod: https://minecraft.curseforge.com/projects/vampirism-become-a-vampire
Source code: https://github.com/TeamLapen/Vampirism

**Comment by Xalcon** [comment]
This is not a bug on my end. The Mod is not using the Forge Spawn Events to check if spawning is allowed. I cant do anything about this. The Author of this mod needs to fix it on his end.
