### ISSUE TITLE
[1.12.2] Zombie Awareness 

### ISSUE THREAD

**Issue by GWSheridan** [Xalcon/TorchMaster#51]
Zombie Awareness mod allows Zombies to spawn with a mega torch down 

Version
Zombie Awareness: 1.11.11
TorchMaster: 1.6.1.53
Forge: 14.23.1.2608
MC: 1.12.2

**Comment by Xalcon** [comment]
This is not a bug on my end. I cant do anything about this, it seems Zombie Awareness is not using the Forge Spawn Events which Torchmaster relies on. Please report this to the Author of Zombie Awareness if you want this to be fixed.
