### ISSUE TITLE
Fails to remove from registry

### ISSUE THREAD

**Issue by LemADEC** [Xalcon/TorchMaster#57]
As of torchmaster_1.12.2-1.6.1.53.jar, when regenerating a chunk, the console gets spammed with error about removing torches from registry. Those logs keep on coming, which means the registry doesn't actually get cleaned.
Also, this prevents chunks to be unloaded.

**Comment by TheSnowyChickens** [comment]
I have the same issue.

**Comment by Xalcon** [comment]
fixed with PR #54
