### ISSUE TITLE
Disable Mega Torch using Redstone

### ISSUE THREAD

**Issue by Xalcon** [Xalcon/TorchMaster#6]
Just that: Disable Mega Torch using redstone

**Comment by Xalcon** [comment]
Feature scraped for now. In playtest this caused some major issues and after talking to a few people, there is no major benefit in keeping this feature. If you need to disable a torch, block breakers and placers might be an alternative. Someone on my server suggested using a dispenser, but this would require some runtime vanilla code modifications, which I try to stay away from.

**Comment by Peekofwar** [comment]
Huh... No redstone mega torch then. Though, I am curious of what kind of issues were encountered.
