### ISSUE TITLE
[suggestion] Confining the Wither

### ISSUE THREAD

**Issue by stohun01** [Xalcon/TorchMaster#62]
Something that creates a configurable sized region that neither the Wither or its projectiles can escape. The intended use is for building a colosseum or arena for fighting the Wither.

**Comment by Xalcon** [comment]
I've thought about this for a while now and I'm not sure how this could be implemented in a configurable way without making it too confusing for players or too complex in code.

I also dont want to add too much bloat to torchmaster. TorchMaster is about spawning control and lighting. But let this discourage you. If we find a suitable way to implement this, I'm happy to do this.

**Comment by Xalcon** [comment]
i think this exceeds the scope of the mod. This feature should be its own mod.
