### ISSUE TITLE
Sponge Incompatability

### ISSUE THREAD

**Issue by paulccorey** [Xalcon/TorchMaster#63]
A server running sponge will negate the effect of mega torches upon restart. Breaking and replacing the torches fixes the issue.  But obviously this is not ideal.

Let me know if this is something I should instead report on the sponge site, and I'll write one up there!

**Comment by paulccorey** [comment]
Using version 1.12.2 1.6.1.53 that comes with the Nature's beauty mod pack.

And here's the boot up log from the last time we booted the server up using sponge:

https://pastebin.com/YgQGWkw3

**Comment by Xalcon** [comment]
can you please update to 1.6.4.62 and try again? I've fixed a similar issue in said release and it wouldnt surprise me if those issues are somewhat related.

**Comment by paulccorey** [comment]
Would all the clients need to update, or can it just be a server side change?

**Comment by Xalcon** [comment]
A server side update should be fine for this.

**Comment by paulccorey** [comment]
Alright, I'll test it out tonight, and let you know how it goes!

**Comment by Xalcon** [comment]
Due to inactivity in this issue, i'll close this. We can re-open this if this issue persists.
