### ISSUE TITLE
[Suggestion] Cave ambience suppression

### ISSUE THREAD

**Issue by ItsTheKais** [Xalcon/TorchMaster#65]
Spawn prevention lets you use darkness in builds, but using darkness causes spooky noises! It would be pretty nice if the mega torch prevented cave ambience sounds from playing within its radius. (or a separate device for that, doesn't really matter I guess??)

**Comment by Xalcon** [comment]
hm, interesting idea. I'm not sure if this is currently possible but I'll look into it.

**Comment by Xalcon** [comment]
feature has been implemented and will be released with Torchmaster v1.7
