### ISSUE TITLE
Crash with JEI, FTB Revelation

### ISSUE THREAD

**Issue by Lear85** [Xalcon/TorchMaster#66]
Occasionally, upon attempting to look up item recipes for various items, game will crash, and launcher will display the following error.

`Error: java.lang.RuntimeException: ItemBlock 1xtile.torchmaster.mega_torch@0 returned an unregistered block from getBlock().`

Crashes happen seemingly at random, upon attempt to retrieve recipes through JEI. Seemingly no pattern on what items cause crash, or when.

Logfile attached.
[2018-08-05-2.log](https://github.com/Xalcon/TorchMaster/files/2260146/2018-08-05-2.log)

EDIT: I've discovered that looking up the recipe for Quite Clear Glass causes a crash consistently. The launcher still claims the issue is a call made by TorchMaster

**Comment by Xalcon** [comment]
This is a rather odd issue. I'm not doing anything special, all block instances are also registered - there might be some block instances that dont have an item variant, but mods should not expect that all blocks have an item counter part. I'll definitely take a closer look into this issue but I'm not sure if this really on my end. Thanks for the report though.

**Comment by Lear85** [comment]
It's possible the server I'm on removed Torchmaster, which could be the cause of the issues. I'll forward the report on to Ender IO as well. Thank you for your assistance!

**Comment by Xalcon** [comment]
I've just tried to replicate this issue, without success. Make sure you are using the latest versions for all mods and forge. They might have fixed it already.
