### ISSUE TITLE
Frozen Pearl description. Feral Fire or Feral Flare?

### ISSUE THREAD

**Issue by Revvilo** [Xalcon/TorchMaster#67]
Is it just me, or is it meant to be Feral ***Flare*** lantern on the Frozen Pearl?

<img src="https://user-images.githubusercontent.com/13816212/43807712-dc94e724-9afd-11e8-9bea-2926b0572db3.png">
<img src="https://user-images.githubusercontent.com/13816212/43807756-0af70976-9afe-11e8-80ab-ed975f5b74f8.png">

Every time I look at that item I wonder. 🤔

**Comment by Xalcon** [comment]
Oh crap, someone noticed... I tested an issue with the lantern yesterday and noticed this myself. I was hoping nobody would see it >_> whelp. Will be fixed next release.
