### ISSUE TITLE
Lightblocks cause issuse with hollow Multiblocks

### ISSUE THREAD

**Issue by Swabek** [Xalcon/TorchMaster#72]
Mods like Gregtech have some Multiblocks that are only valid if there are hollow (only air inside). 
Lightblocks from "Feral Flare Latern"  inside such multiblocks leads to invalid structures.

Please see: GregTechCE/GregTech#454

**Comment by Xalcon** [comment]
I did some testing and it seems its a bit more complicated than that.

I register my block with `Material.AIR`. `Block#isAir()` simply checks if the material of the block is `Material.AIR` - therefor, I already return true for the `isAir()` check.

As is stands right now, I dont think I can fix this easily, if I can fix this at all.
It seems gregtech doesnt check for `Block#isAir()` but for the blockstate - which is obviously different from air.

**Comment by Xalcon** [comment]
Sadly, i cannot fix this issue on my end. I'm already doing everything I should. Gregtech needs to handle pseudo-air blocks properly. Sorry :(

If you have anything else, feel free to create a new issue or respond to this one. I'll close this for now.
