### ISSUE TITLE
Feral Flare Lantern infinitely growing light data

### ISSUE THREAD

**Issue by Willsr71** [Xalcon/TorchMaster#80]
The Feral Flare Lantern has the capability to apparently nonstop grow the amount of light sources it stores.
For context, I placed a lantern near the sky height in the modpack StoneBlock and shortly after doing so nobody was able to go near that chunk without being kicked from the server with a Badly compressed packet exception.

This screenshot is of a program I wrote to determine what the largest TileEntity was in a chunk to help resolve the badly compressed packet error, and it turned up that this lantern was by *far* the largest block
![image](https://i.imgur.com/CP0zsf4.png)
The light list continuously grows. Infinitely. My theory is that it tries to place blocks above the world height limit and then fails to detect that they are actually there, so tries placing more and repeat cycle. That or the world limit prevents light levels from ever being satisfactory on the topmost block.

Image of setup:
![image2](https://i.imgur.com/IMj1GaE.jpg)
Badly compressed packet exception:
![image3](https://cdn.discordapp.com/attachments/177743634731499520/530208620692897826/unknown.png)

**Comment by Xalcon** [comment]
oh.... shit. Yeah, that might be a thing. Another edgecase I've never even thought of. Ty for reporting this, I'll try putting out a fix asap. Btw, which version of the Mod are you using?

**Comment by Xalcon** [comment]
Fixed in 1.7.1.74 for 1.12. Should be available soon on curseforge.

**Comment by Xalcon** [comment]
I just realised.. those project:e watches probably accellerated the issue. How long did you run this setup before you noticed this bug?
I'm considering adding a more sensible hard limit, just in case something else can cause this issue as well.

**Comment by Willsr71** [comment]
The block was placed about a day before any issues were noticed, but probably closer to 20 hours before it would actually happen. The version was 1.7.0.72.

**Comment by Xalcon** [comment]
thanks for the detailed response :) I'll close this then.
