### ISSUE TITLE
Mega Torch Show Area via Enchantment, Upgrade etc..

### ISSUE THREAD

**Issue by ReportBot9009** [Xalcon/TorchMaster#86]
I was wondering if the Mega Torch could get an upgrade, like an ender eye or ghast tears/diamonds/whatever to make ghost blocks kind of like Immersive Engineering or the Open Blocks Building guide? 

I ask this because I'd love to have perfectly spaced torches. I know it's a 32 block radius with 64 in a square, but something observable as an upgrade or interaction would help me, and maybe others...

Thanks for at least listening :)

**Comment by Xalcon** [comment]
If you just want to space it perfectly, you can simply rightclick any dye to show its bounds. I try to avoid using ghost blocks due to their massive performance impact with big torch ranges. I might revisit ghost blocks in the future, but the currently available visualizer should be sufficient to space out torches perfectly.

**Comment by ReportBot9009** [comment]
Ah. 

You mean right clicking the torch with a dye in your hand? I'm trying that right now and not seeing anything. I do have Optifine installed on Project Ozone 3, so maybe a conflict?

What about when you press F9 and it shows you chunk boundaries? Those are not performance intensive. Maybe that instead of ghost blocks...

**Comment by Xalcon** [comment]
The F9 rendering boundaries is more or less how I do it. Make sure you are using the latest version of torchmaster. I dont know if optifine causes any issues, but I wouldn't be surprised. It's hard to be compatible with mods that are closed source.

**Comment by benjamin-kirkbride** [comment]
@Xalcon sorry to necro, but are you saying that right clicking a placed megatorch with say, an ink sac should result in some bounds being rendered? I also can't get this to work.

**Comment by benjamin-kirkbride** [comment]
Oh, did this used to be a thing but is no longer a thing? https://github.com/Xalcon/TorchMaster/issues/206

**Comment by Xalcon** [comment]
This is currently only working in 1.20. I need to optimize it for 1.21 but time is a bit of an issue at the moment.
