### ISSUE TITLE
Remove tooltip doesn't remove Frozen Pearl tooltip

### ISSUE THREAD

**Issue by SynexWolf** [Xalcon/TorchMaster#87]
Minecraft: 1.12.2
Forge: forge-14.23.5.2824
TorchMaster: torchmaster_1.12.2-1.7.1.74

When setting beginner tooltips to false, it doesn't remove the frozen pearl tool tip.

**Comment by Xalcon** [comment]
i actually dont recall why I even added the beginner tooltips option, but oh well :P It makes sense that all/most the tooltips can be controlled by that setting I guess.
