### ISSUE TITLE
[1.14.3] Dedicated server crash on load. Sidedness issue?

### ISSUE THREAD

**Issue by ProsperCraft** [Xalcon/TorchMaster#90]
Crash report
https://gist.github.com/ProsperCraft/00abb71e29e0cfb30cd9c2e17d6aa320

Relevant section of the log-
https://gist.github.com/ProsperCraft/95c8692ab6fdead67648859e29b2acfa

Debug log-
https://gist.github.com/ProsperCraft/62f6478ffb7d7ae92e8955197dcf9618

Modpack-
https://www.curseforge.com/minecraft/modpacks/ocean-islands-adventure

**Comment by Xalcon** [comment]
fixed in v2.0.0.1-alpha, should be available on curseforge shortly.
