### ISSUE TITLE
[1.14.3] Lycanites Mobs bypass the mega torch anti-spawning.

### ISSUE THREAD

**Issue by ProsperCraft** [Xalcon/TorchMaster#92]
https://gitlab.com/Lycanite/LycanitesMobs/issues/518

**Comment by Xalcon** [comment]
Please provide more info.
Mod Versions, Forge Version, torch setup, what is spawning, etc.

**Comment by ProsperCraft** [comment]
forge-1.14.3-27.0.50

torchmaster-2.0.0.1-alpha

lycanitesmobs-1.14.3-2.1.0.0-beta07

more then one torch is placed around the base, and all hostile vanilla mobs are blocked from spawning, but lycanites due to their unique spawning mechanism spawn all over the base and destroy blocks.

**Comment by Xalcon** [comment]
I'm unable to track down any "unique spawning mechanism" in lycanites mobs. Do you have any more information on this?

I've tried replicating the issue in my local dev instance and everything was working as expected. There were quite a few lycanite mob spawns, but nothing inside the torch volume.
Please keep in mind, the torch only blocks spawning inside the torch volume, it doesnt prevent mobs from walking into it. 

I'd like to ask you to verify that the entities actually spawn inside the volume and dont just path towards you after spawning outside the volume.

**Comment by Xalcon** [comment]
I'll close this due to inactivity. If someone is able to replicate this, please add to this issue. We can re-open it in case it's still an issue.
