### ISSUE TITLE
[1.14.4] Please update there is a hard dep on 1.14.3

### ISSUE THREAD

**Issue by ProsperCraft** [Xalcon/TorchMaster#93]
![b58d02008307aa81bb408c57374c6f4a](https://user-images.githubusercontent.com/4427684/62137803-cf5e7c00-b2a3-11e9-9c3f-33518e7b13bf.png)

**Comment by Xalcon** [comment]
I'm preparing another build that should work with 1.14.4.
Should be available on curseforge later today

**Comment by Xalcon** [comment]
release is available on curseforge
