### ISSUE TITLE
JsonSyntaxException at version check

### ISSUE THREAD

**Issue by florian-redinger** [Xalcon/TorchMaster#95]
When starting my Forge Server I get an error at the version check. I tried the alpha version of 1.14.

I've attached the part of the server output showing the error.
[errorMessage.txt](https://github.com/Xalcon/TorchMaster/files/3477467/errorMessage.txt)

**Comment by Xalcon** [comment]
looks like forge moved a class into a different package which causes a crash during mod loading. The error you get doesn't tell the full story. I'll make a fix, should be up on minecraft forge in around an hour.

**Comment by Xalcon** [comment]
fixed in 2.0.0.5-alpha (awaiting approval on curseforge, shouldnt take long)
