### ISSUE TITLE
[1.14.4] NullPointer

### ISSUE THREAD

**Issue by florian-redinger** [Xalcon/TorchMaster#96]
When starting the Forge Server there is a NullPointer when loading the mod.

I've appended the complete stack trace.
[errorMessage.txt](https://github.com/Xalcon/TorchMaster/files/3478529/errorMessage.txt)

I can provide a server for testing, if it helps.

**Comment by Xalcon** [comment]
I'm not sure why you think that torchmaster is the issue here. Torchmaster is currently available with the version 2.0.0.5-alpha and requires forge 28.0.45+
You are using forge 28.0.34. Why do you think Torchmaster is the issue and which version of torchmaster are you using?

**Comment by florian-redinger** [comment]
Normally the server throws some sort of version mismatch error and simply doesn't load the mod. However Torchmaster caused it to completely crash. That's why I was a bit confused and was also the reason why I wanted to post about it.
Obviously that explains why it doesn't work.

**Comment by Xalcon** [comment]
It depends. Version 2.0.0.4 didn't have a version requirement but was broken with certain forge builds. I fixed that with 2.0.0.5 and set the minimum version to 28.0.45 since thats the version I've tested the mod with.

**Comment by florian-redinger** [comment]
Yes it does work with 28.0.45
