### ISSUE TITLE
Grimoire of Gaia Compatability?

### ISSUE THREAD

**Issue by Azuriuz** [Xalcon/TorchMaster#99]
Hey there, it doesn't seem like the mega torch is preventing grimoires mobs from spawning. I was wondering if there could be some compatability configs in the future to help with this?

**Comment by Xalcon** [comment]
Which mod versions are you using? I'm using gog in my private 1.12 pack and didn't have any issues. The last release of torch master even added a white/blacklisting option for the 1.12 version.

**Comment by Azuriuz** [comment]
Sorry, 1.12.2
I will try updating and see if it helps!

**Comment by Xalcon** [comment]
Sure, please report back. I noticed that GoG spawns highly depend on the biomes you are in, so I might just be lucky. If there are any outliers, I'll add support for them to torchmaster. In the meantime you should be able to add entities to the config manually.

**Comment by Azuriuz** [comment]
I'm going to be trying to blacklist all the gaia mobs I guess; but just fyi the mega torch still does not stop hostile or neutral spawns from grimoire of gaia. 
As this is a pretty popular mod full of highly aggressive mobs, I would highly suggest looking into a config to turn the mob spawns off for that mod? It would really be helpful for my modpack and I'm sure anyone who uses both of these mods would agree with me.

**Comment by Xalcon** [comment]
I will check this once I'm done with the 1.14 release. In the meantime, the blacklist should work - but i definitely want to support GoG out of the box.

**Comment by Azuriuz** [comment]
I'm testing in the next few days on whether the blacklist works in the meantime, I'll let you know if there's any issues there. Thank you!

**Comment by Xalcon** [comment]
I finally got around testing this and I dont see any issues. YES, there are some spawns happening, but only neutral ones like minotaurs (which can mostly be blocked with the dread lamp)

**Comment by Azuriuz** [comment]
As of the last update it looks like only neutral spawns are spawning! Thank you~
